### ISSUE TITLE
Can't configure kotlinOptions after upgrade to gradle 5.6.3 using kotlin-dsl

### ISSUE THREAD

**Issue by b95505017** [gradle/gradle#11083]
```
  Line 172:         jvmTarget = "1.8"
                    ^ Unresolved reference: jvmTarget

  Line 173:         freeCompilerArgs = freeCompilerArgs + listOf(
                    ^ Unresolved reference: freeCompilerArgs

  Line 173:         freeCompilerArgs = freeCompilerArgs + listOf(
                                       ^ Unresolved reference: freeCompilerArgs
```

**Comment by eskatos** [comment]
Thanks for the report @b95505017 
It's impossible to tell what is happening without knowing what's above this "Line 172".
Could you please tell us a bit more, sharing a reproducer would be ideal.

**Comment by robinlinden** [comment]
I run into the same issue after updating to 5.6.3 (https://github.com/robinlinden/aTox/tree/gradle-5.6.3):

```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projects\aTox\app\build.gradle.kts' line: 33

* What went wrong:
Script compilation errors:

  Line 33:         jvmTarget = Java.version.toString()
                   ^ Unresolved reference: jvmTarget

  Line 34:         freeCompilerArgs = listOf("-XXLanguage:+InlineClasses")
                   ^ Unresolved reference: freeCompilerArgs

2 errors
```

https://github.com/robinlinden/aTox/blob/c47d912be488c1e5ef7c76d2e740953231702eec/app/build.gradle.kts#L12-L35

**Comment by eskatos** [comment]
With Gradle 5.6.2, `android.kotlinOptions {}` is a generated accessor for the `kotlinOptions` extension of type `org.jetbrains.kotlin.gradle.dsl.KotlinJvmOptions` on the `android` extension.

With Gradle 5.6.3, that same accessor is typed `Any`.

**Comment by eskatos** [comment]
You can work around that by using the API instead of the generated accessor:
```kotlin
android {
    (this as ExtensionAware).configure<KotlinJvmOptions> {
        jvmTarget = "1.8"
    }
}
```
or by using the more dynamic Groovy builder:
```kotlin
android {
    withGroovyBuilder {
        "kotlinOptions" {
            setProperty("jvmTarget", "1.8")
        }
    }
}
```

**Comment by b95505017** [comment]
@eskatos Will future version change back?

**Comment by jjohannes** [comment]
Fix for 6.0 (#11171) is now on `release`

**Comment by bamboo** [comment]
Fir for 5.6 (#11191) is now on `release-5.6`.
