### ISSUE TITLE
library imported to eclipse classpath as module because of existence of Automatic-Module-Name manifest entry

### ISSUE THREAD

**Issue by urferr** [gradle/gradle#16737]
### Expected Behavior
The dependent library may not have the classpath attribute `module=true` just because the manifest entry `Automatic-Module-Name` has been defined

### Current Behavior
the classpath attribute `module=true` is defined and therefore i get a compile issue in eclipse because of multiple definition of a package (`The package javax.annotation is accessible from more than one module: <unnamed>, java.annotation`). This problem has been introduce with gradle 7.0 (rc1 and rc2), it was working fine with gradle 6.8.3 and before.

### Steps to Reproduce 
Import the attached gradle project into Eclipse Java IDE using buildship plugin and you will get the error. If you switch the used gradle version the 6.8.3 the compile issue disappears.

[testGradle7.zip](https://github.com/gradle/gradle/files/6272478/testGradle7.zip)

### Your Environment
Eclipse IDE for Java Developpers 2021-03
JDK 15
gradle 7.0-rc-2

**Comment by ljacomet** [comment]
Your sample makes use of private libraries. Please provide a reproducer that works outside of your organization.

Note that there was a [change around Java modules handling](https://docs.gradle.org/current/userguide/upgrading_version_6.html#modularity_infermodulepath_defaults_to_true) in Gradle 7.

**Comment by urferr** [comment]
sorry, you can just delete the buildSrc folder, it's not used to reproduce the problem, i forgot that.

**Comment by urferr** [comment]
when i set modularity.inferModulePath = false then it works also with gradle 7.0

**Comment by donat** [comment]
Duplicate of #16922.
