### ISSUE TITLE
8.1 RC 1: Regression in JUnit5 parameterized tests

### ISSUE THREAD

**Issue by davidburstromspotify** [gradle/gradle#24429]
### Current Behavior

Tests with `@ParameterizedTest` and `@MethodSource` no longer works, throwing
```
java.lang.NoSuchMethodError: 'java.lang.String[] org.junit.platform.commons.util.ReflectionUtils.parseQualifiedMethodName(java.lang.String)'
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.getFactoryMethodBySimpleOrQualifiedName(MethodArgumentsProvider.java:105)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.getFactoryMethod(MethodArgumentsProvider.java:69)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$provideArguments$0(MethodArgumentsProvider.java:54)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
...
```
during initialization.

### Context

It works in 8.0.2, not in 8.1-rc-1.

### Steps to Reproduce 

Run the attached project with `./gradlew test`.
[gradle-8.1-rc-1-parameterized-tests.tgz](https://github.com/gradle/gradle/files/11031418/gradle-8.1-rc-1-parameterized-tests.tgz)

### Your Environment

Build scan URL: https://scans.gradle.com/s/uzpq7lp7gox5e

**Comment by jvandort** [comment]
Thank you for filing this regression report with a valid reproducer. It appears this issue was introduced in this commit: https://github.com/gradle/gradle/commit/b9ca68b54787740fcd0247d52fadb223d9576765

Below is a description of the problem in detail. I am writing it here to document the problem, though we will be discussing a proper solution internally. For now, if you wish to continue using 8.1 RC1, you can declare a `testRuntimeOnly` dependency on `junit-platform-launcher`. 

Coming to a proper solution here is difficult. When using junit platform, Gradle sometimes loads junit platform jars from its own distribution. This is legacy behavior which we will be deprecating shortly and will be removed in 9.0. In particular, Gradle loads the junit-platform-launcher jar and its dependencies, junit-platform-engine and junit-platform-commons. A major issue can arise if the junit jupiter jars from the test runtime classpath differ in version compared to the junit platform jars which are present in the gradle distribution.  

This change was introduced while trying to phase out this behavior. We attempt to detect whether the junit-platform-laucnher jars and its dependencies are present, and if so, we do not load the dependencies from the distribution. While implementing this, we switched the ordering on the test classpath to put these loaded jars _first_, since a very similar problem to what you are facing here can occur. 

In this case, your test runtime classpath does not contain junit-platform-launcher, so gradle loads it from the distribution, and junit-platform-commons, but at a lower version. This version does not contain the method `parseQualifiedMethodName` in junit-platform-commons, leading to the exception in the reproducer. 

The other way around is also possible. If the test runtime classpath has junit-platform-commons with a lower version than what the distribution loads for junit-platform-launcher, then the version we load from the distribution may reference junit-platform-commons methods which do not exist. 

The root cause of the problem here is differing versions of the same library on the classpath at once. We will try to find a solution here, but solving this will break other use cases with similar but reversed version combinations.

**Comment by jvandort** [comment]
Our immediate solution here will be to reverse the classpath ordering back to the way it was. With the previous ordering, the version conflict issue appears to isolated to running Gradle's embedded integration testing only -- and only when running with GE test distribution. This previous ordering, which we are going back to, seems to work for users in general. 

In the long run, we are going to deprecate the behavior of loading the junit-platform-launcher jar from the distribution at all. Expect a deprecation for that coming up in recent versions. I would recommend supplying your own version of the jar anyways, even if the fix for this solves your issue. 

But yes, as you said, Gradle itself is compatible with a range of junit versions. We aim to be compatible with whatever version of junit-platform-launcher you provide on the classpath.

**Comment by jvandort** [comment]
@davidburstromspotify The fix has been merged. Would you be able to confirm with tonight's nightly to make sure this fixed your issue?

**Comment by davidburstromspotify** [comment]
I've verified that it works with 8.1-20230324001534+0000, thank you!
