### PR TITLE
Update eclipse.gradle for importing gradle without compile errors into Eclipse 

### PR DESCRIPTION
**Pull request by zosrothko**
Any of the checked boxes below indicate that I took action:

- [x] Reviewed the [Contribution Guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contribution-workflow).
- [x] Signed the [Gradle CLA](http://gradle.org/contributor-license-agreement/).
- [x] Ensured that basic checks pass: `./gradlew quickCheck`

Hi

This PR is a fix to the gradle/eclipse.gradle script. It permits to import later on all gradle projects with no compile errors in all src/main/java classes and most of all but few src/test/groovy classes.
By adding the build/generated-resource/main to the classpath of each project, gradle can run as a simple non daemon java application ready to be debugged under the Eclipse JDT debugger.

Using the JavaSE-1.8 is mandatory since JavaSE-1.7 compiles some gradle java classes with errors.

### CODE REVIEW

**Comment by donat** [comment]
Thank you for the contribution!

Can you please elaborate what doesn't work without your patch?

Also, I think changing the Java version should not necessary, as Gradle can be built and works on Java 7.  I did see an incompatible class exception when experimented with your changes, but it turned out that was because the settings changed by the `eclipse` Gradle plugin were not picked up by Eclipse. The problem disappeared when I first called `gradle eclipse` and then restarted Eclipse.

**Comment by zosrothko** [comment]
Hi

When importing gradle into Eclipse with a 1.7 JDK and a JAvaSE-1.7, one gets the following errors
```
Description    Resource    Path    Location    Type
The method addAll(Collection<? extends T>) in the type List<T> is not applicable for the arguments (List<Object>)    CollectionUtils.java    /baseServices/src/main/java/org/gradle/util    line 240    Java Problem
Description    Resource    Path    Location    Type
Type mismatch: cannot convert from Pair<capture#2-of ? extends T,R> to Pair<T,R>    Pair.java    /baseServices/src/main/java/org/gradle/internal    line 68    Java Problem
```
When importing the same gradle into Eclipse with the 1.8 JDK and JAvaSE-1.8, there is no error

I know that gradle builds with the 1.7 JDK in the CI but that's a pure CLI JDK 1.7 invocation. While in Eclipse, only the JDK 1.8 works.

**Comment by donat** [comment]
I did an investigation and turned out that the source of the compilation errors is [in the Eclipse Java Compiler](https://bugs.eclipse.org/bugs/show_bug.cgi?id=342267). Technically, we could fix it by adjusting the codebase to make it compile in Eclipse, but it would be prone for accidental breakages (for example look at the fix in #200 and how 8e5b47a084ebbb7ee1588b5765c998256e42aa67 broke it).

Consequently, simply using Java 8 in Eclipse is a better solution IMHO.

**Comment by zosrothko** [comment]
Thank for accepting this PR... One can now debug gradle as a non daemon under eclipse.

**Comment by donat** [comment]
Thank you for submitting this pull request! I've added your name to the [Gradle 3.3 release notes](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/release/notes.md#external-contributions).

**Comment by donat** [comment]
Internal review: https://code-review.gradle.org/cru/REVIEW-6343
