### ISSUE TITLE
Support forked compilation with Java 9

### ISSUE THREAD

**Issue by dieterstueken** [gradle/gradle#3035]
### Expected Behavior
Compiling  the samples on [building-java-9-modules](https://github.com/gradle-guides/building-java-9-modules) should work with gradle 4.2.0 and a forked Java 9 compiler, too.
### Current Behavior
Running with `options.fork = true` fails with

> .../main/java/module-info.java:1: error: file should be on source path, or on patch path for module
> module org.gradle.actors {
> ^
### Context
Running gradle with Java9 (build 9+181) directly uses the internal [JdkJavaCompiler](https://github.com/gradle/gradle/blob/v4.2.0/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java). For a forked compiler some external [CommandLineJavaCompiler](https://github.com/gradle/gradle/blob/v4.2.0/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/CommandLineJavaCompiler.java) is used instead. I like to use a forked compiler to possibly run gradle with Java8 to cross compile Java9.

While the JdkJavaCompiler provides a [hack](https://github.com/gradle/gradle/blob/v4.2.0/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java#L64) to suppress empty `--source-path` options for Java9, this seems to be missing for the CommandLineJavaCompiler (see resulting `build/tmp/compileJava/java-compiler-args.txt`).

### Steps to Reproduce (for bugs)
Using the samples from [building-java-9-modules](https://github.com/gradle-guides/building-java-9-modules) at [build.gradle](https://github.com/gradle-guides/building-java-9-modules/blob/f61ec74ba35bfc4bf643d3843c1e589f374cc090/src/2-all-modules/build.gradle#L10) I added some fork options (use an appropriate JAVA path on your system)
```
            doFirst {
                options.fork = true
                options.forkOptions.javaHome = file('C:/Program Files/Java/jdk-9')
                options.compilerArgs = [
                       '--module-path', classpath.asPath,
                ]
                classpath = files()
            }
```
A workaround is adding some user defined `source-path` option like:
```
            doFirst {
                options.fork = true
                options.forkOptions.javaHome = file('C:/Program Files/Java/jdk-9')
                options.sourcepath = files(sourceSets.main.java.srcDirs)                
                options.compilerArgs = [
                    '--module-path', classpath.asPath,
                ]
                classpath = files()
            }
```
Interestingly there is already an internal function[`JdkJavaCompiler.noEmptySourcePath()`](https://github.com/gradle/gradle/blob/e6eaf2462296586b1c2038fb7bd20cb8818f0e88/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JavaCompilerArgumentsBuilder.java#L75) . But i can't find any usage beside some unit tests. 

### Your Environment

> $ ./gradlew -version
> ------------------------------------------------------------
> Gradle 4.2
> ------------------------------------------------------------
> 
> Build time:   2017-09-20 14:48:23 UTC
> Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd
> 
> Groovy:       2.4.11
> Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
> JVM:          9 (Oracle Corporation 9+181)
> OS:           Windows 10 10.0 amd64

Just realize that I run gradle itself on Java9, too. Running gradle with Java8 still produces some additional issues concerning the tests build&run.

**Comment by eximius313** [comment]
With Gradle 4.6, when I'm using `options.fork = true` I get:
```
:compileJavaWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.gradle.api.internal.tasks.compile.reflect.SourcepathIgnoringInvocationHandler (file:/Users/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6/lib/plugins/gradle-language-java-4.6.jar) to method com.sun.tools.javac.file.BaseFileManager.handleOption(java.lang.String,java.util.Iterator)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.compile.reflect.SourcepathIgnoringInvocationHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
which is not appearing with `options.fork = false`

**Comment by oehme** [comment]
Closing as outdated, forked compilation with Java 9 works just fine since several releases.
