### ISSUE TITLE
some of gradle builds failing after firing refresh-dependencies command

### ISSUE THREAD

**Issue by hlms** [gradle/gradle#12644]
gradlew :myProject:compileJava results into the following error:

```
MyProvider.java:24: error: cannot access Provider
public class MyProvider<T> implements Provider<T> {
       ^
  class file for javax.inject.Provider not found
An exception has occurred in the compiler (1.8.0_181). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.NullPointerException
        at com.sun.tools.javac.comp.Attr.visitTypeParameter(Attr.java:4016)
        at com.sun.tools.javac.tree.JCTree$JCTypeParameter.accept(JCTree.java:2224)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
        at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4296)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
:myProject:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':myProject:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 13.098 secs
```

### Expected Behavior

* Build should succeed.
* It was successful earlier. Just when I performed refresh-dependencies command, the build started failing.
* My team-mates, who have NOT performed refresh-dependencies command, are facing no issues. They can still successfully build the same project version with same gradle/java settings.

### Current Behavior

* The build is failing as mentioned above.
* In the debug logs, I can see the following:
```
:myProject:compileJava (Thread[Task worker Thread 7,5,main]) started.
:myProject:compileJava
Executing task ':myProject:compileJava' (up-to-date check took 0.042 secs) due to:
  Output file /project/path/in/my/system/MyProvider.class has been removed.
  Output file /project/path/in/my/system/RetrofitErrorHandler.class has been removed.
  Output file /project/path/in/my/system/RetrofitRxRetrier.class has been removed.
All input files are considered out-of-date for incremental task ':myProject:compileJava'.
Compiling with JDK Java compiler API.
:myProject:compileJava FAILED
:myProject:compileJava (Thread[Task worker Thread 7,5,main]) completed. Took 0.84 secs.
```

### Context

This is one of the issues I'm facing.  
For other projects also, I see uncanny build failures whereas other team members can build those projects successfully.

### Steps to Reproduce 

Create a java web application, and a class which implements com.google.inject.Provider<T> class of guice-3.0. That's what my scenario is. I don't have clear reproduction steps. Some of gradle directories seems to have been corrupted due to refresh-dependencies.

### Your Environment

```
------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.12.6 x86_64
```

Build scan URL: NA

### Note
I asked the question on stackoverflow also: https://stackoverflow.com/q/60830913/4270739

**Comment by ljacomet** [comment]
Given that you are using Gradle 2.14.1, the main recommendation is to upgrade Gradle.
Even if you were to identify a Gradle bug, there would not be a bugfix release againt 2.x given that Gradle is now at 6.x.

Otherwise, check what happens when running a clean build, that is a different checkout of the project.

**Comment by hlms** [comment]
@ljacomet ,  
Agree.  
It would be great if some work-around can be suggested.  
If there is something that can be fixed in my settings, that's what I ~~want~~ need.

**Comment by ljacomet** [comment]
From least destructive to most destructive:
* Try running a `clean` before a build
* Try removing `~/.gradle/caches/modules-*` (nuking your dependency cache)
* Try removing `~/.gradle` and `<project>/.gradle` Nuking _all_ caches

**Comment by hlms** [comment]
@ljacomet 
What I attempted to resolve the issue:
1. Checked in old version of my code. Build fails with the same error.
1. Clearing ~/.gradle/caches and ~/.gradle directories
1. Upgraded gradle to 3.5 (build failed), and then downgraded back to 2.14.1 (still same issue)
1. Removing entire source code repository and then downloading it again was NOT done because recently one of my colleagues attempted to set-up it from scratch, and he faced this issue. So, I don’t think it would work for me.
 1. Performed all the cleaning methods suggested by you.

Do you suggest us to update the gradle to latest version?

What version of gradle will work with Java 8? Is gradle version 6.3 compatible with Java 8 or do we need to update to some other gradle version?

**Comment by hlms** [comment]
@adammurdoch , @bigdaz ,  
Any comments?

**Comment by hlms** [comment]
@ldaley , @bamboo ,  
Any comments?

**Comment by hlms** [comment]
@ljacomet,
I upgraded gradle to version 6.3 and still the build failed.
```
MyProvider.java:24: error: cannot access Provider
public class MyProvider<T> implements Provider<T> {
       ^
  class file for javax.inject.Provider not found
```

The project containing MyProvider.java depends on com.google.inject.Provider<T> of guice-3.0, and guice-3.0 depends on javax.inject.Provider<T>.

The compiler errors about javax.inject.Provider.

When I looked into the .pom file for guice-3.0, it does NOT have any dependencies mentioned.
guice-3.0.pom file location:

```
$ pwd
~/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/3.0
$ tree
.
├── 5a106815122ba3584f77006351bfad65f302bcc
│   └── guice-3.0.pom
├── 9d84f15fe35e2c716a02979fb62f50a29f38aefa
│   └── guice-3.0.jar
└── d117c4481f64955cb1862ed38cb568add2f5fe05
    └── guice-3.0-sources.jar
```
The aforementioned files get downloaded from our internal artifactory (and NOT from maven website).

guice-3.0.pom:
```xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">  
  <modelVersion>4.0.0</modelVersion>  
  <groupId>com.google.inject</groupId>  
  <artifactId>guice</artifactId>  
  <version>3.0</version>  
  <packaging>jar</packaging>  
  <name>Google Guice - Core Library</name>  
  <description>Google Guice Core Library</description>  
  <url/>  
  <licenses> 
    <license> 
      <name>Apache-2.0</name>  
      <url>http://www.talendforge.org/modules/licenses/APACHE_v2.txt</url> 
    </license> 
  </licenses> 
</project>
```

Whereas when I looked into guice-3.0.pom from [maven website](https://mvnrepository.com/artifact/com.google.inject/guice/3.0), it does mention about dependencies:

```
  <dependencies>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
      <version>1</version>
    </dependency>
    <dependency>
      <groupId>aopalliance</groupId>
      <artifactId>aopalliance</artifactId>
      <version>1.0</version>
    </dependency>
    <!--
     | Replace with official CGLIB artifact when it's released
    -->
    <dependency>
      <groupId>org.sonatype.sisu.inject</groupId>
      <artifactId>cglib</artifactId>
      <version>${cglib.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject-tck</artifactId>
      <version>1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-beans</artifactId>
      <version>3.0.5.RELEASE</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>biz.aQute</groupId>
      <artifactId>bnd</artifactId>
      <version>0.0.384</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.felix</groupId>
      <artifactId>org.apache.felix.framework</artifactId>
      <version>3.0.5</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

Can this cause issues?

**Comment by ljacomet** [comment]
Yes, if you use internal mirrors but they do not mirror the metadata and the dependency information, then it can cause issues.
When you issued your `--refresh-dependencies`, Gradle did fetch all dependency metadata information, overriding what you had in your local cache.
So most likely, your local cache was populated with the correct version of the guice library metadata initially. Then when refreshed you get the version missing dependency metadata.

On a new setup, you get the version missing dependency metadata. If a colleague runs `--refresh-dependencies` he gets the invalid version, and more ...

Fixing your mirroring is the best solution. Or add the necessary explicit dependencies.

Also, please stop mentioning other folks when you have someone interacting with you on an issue.

I will close this now as this is clearly not a Gradle problem.

**Comment by hlms** [comment]
@ljacomet ,  
Thank you confirming the issue.  

(Regret for the inconvenience caused due to tagging more folks. Will take care now onwards.)
