### PR TITLE
Fix incremental compilation for classes with $ in name

### LINKED ISSUE #19257: Incremental java compilation fails when renaming classname with $ character
Issue occurs since Gradle 7.3. Tested with OpenJDK 11 and 13. Tiny reproduction sample is here: https://github.com/horseunnamed/Gradle-change-detection-issue  

### Expected Behavior
Incremental java compilation is successful when classname with $ is renamed (as it is with Gradle 7.2 and earlier versions) 

### Current Behavior
After changing java class name with $ character and running incremental build we get the error:
```
> Task :compileJava FAILED
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Input property 'stableSources' file .../src/main/java/issue/Class$Name.java has been removed.
  Input property 'stableSources' file .../src/main/java/issue/Main.java has changed.
  Input property 'stableSources' file .../src/main/java/issue/Class$NameChanged.java has been added.
Created classpath snapshot for incremental compilation in 0.0 secs.
Compiling with toolchain '/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home'.
Compiling with JDK Java compiler API.
.../src/main/java/issue/Main.java:5: error: cannot find symbol
        new Class$NameChanged();
            ^
  symbol:   class Class$NameChanged
  location: class Main
1 error
Incremental compilation of 3 classes completed in 0.012 secs.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.02 secs.

FAILURE: Build failed with an exception.
```

### Context
On our real world Android-project we had a very harmful impact from this issue when upgrading Gradle version to 7.3.1.
Incremental annotation processor in our project generates some files with dollar sign and this issue silently led us to `ClassNotFoundException` at runtime in some cases. 
It's very serious blocker for us to upgrade from 7.2.

### Steps to Reproduce 
Please see reproduction sample: https://github.com/horseunnamed/Gradle-change-detection-issue  

1. Run build task to compile java project with classname that conatins dollar sign (e.g. `Class$Name.java`) and reference to it somewhere else (from `Main.java` in my reproduction sample)
2. Change classname and reference to it with something that still contains dollar sign
3. Rerun build task
4. Get mentioned incremental compilation error

### Your Environment
Build scan of failed incremental build from reproduction sample: https://scans.gradle.com/s/b4qlo2umn7dms

### PR DESCRIPTION
**Pull request by asodja**
Fixes #19257

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@oehme  If you might find time to review this I would appreciate it

**Review by oehme — APPROVED** [review]
Excellent, thank you!

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java [hunk 1]
```diff
@@ -56,9 +56,20 @@ public FileNameDerivingClassNameConverter(SourceFileClassNameConverter delegate,
...
+        // Classes with $ may be inner classes
         int innerClassIdx = className.indexOf("$");
-        String baseName = innerClassIdx > 0 ? className.substring(0, innerClassIdx) : className;
-        return fileExtensions.stream().map(fileExtension -> baseName.replace('.', '/') + fileExtension).collect(Collectors.toSet());
+        if (innerClassIdx > 0) {
+            String baseName = className.substring(0, innerClassIdx);
+            paths.addAll(fileExtensions.stream()
+                .map(fileExtension -> baseName.replace('.', '/') + fileExtension)
+                .collect(Collectors.toSet()));
+        }
```
Comment (wolfs) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java:70]:
```suggestion
            fileExtensions.stream()
                .map(fileExtension -> baseName.replace('.', '/') + fileExtension)
                .forEach(paths::add)
        }
```

Nit: this would avoid creating a second hash set.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java [hunk 2]
```diff
@@ -56,9 +56,20 @@ public FileNameDerivingClassNameConverter(SourceFileClassNameConverter delegate,
...
+            .collect(Collectors.toSet());
+
+        // Classes with $ may be inner classes
         int innerClassIdx = className.indexOf("$");
-        String baseName = innerClassIdx > 0 ? className.substring(0, innerClassIdx) : className;
-        return fileExtensions.stream().map(fileExtension -> baseName.replace('.', '/') + fileExtension).collect(Collectors.toSet());
+        if (innerClassIdx > 0) {
+            String baseName = className.substring(0, innerClassIdx);
+            paths.addAll(fileExtensions.stream()
+                .map(fileExtension -> baseName.replace('.', '/') + fileExtension)
```
Comment (wolfs) [inline subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java:68]: Would it be worth extracting a method which maps the FQCN to the relative path?

**Review by wolfs — APPROVED** [review]
LGTM! I left some small comments.

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java (hunk 1 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java]: nice, used that

File: subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java (hunk 2 above)
Comment (asodja) [reply subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/FileNameDerivingClassNameConverter.java]: I extracted `baseName.replace('.', '/') + fileExtension)` to a separate method.

**Comment by asodja** [comment]
@bot-gradle test this

**Review by wolfs — APPROVED** [review]
Awesome, LGTM!

File: subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractJavaGroovyIncrementalCompilationSupport.groovy [hunk 3]
```diff
@@ -29,7 +29,7 @@ abstract class AbstractJavaGroovyIncrementalCompilationSupport extends AbstractI
     File source(String... classBodies) {
         File out
         for (String body : classBodies) {
-            def className = (body =~ /(?s).*?(?:class|interface|enum) (\w+) .*/)[0][1]
+            def className = (body =~ /(?s).*?(?:class|interface|enum) ([\w$]+) .*/)[0][1]
```
Comment (lptr) [inline subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractJavaGroovyIncrementalCompilationSupport.groovy:32]: Are there any other characters we are missing here I wonder?

Comment (wolfs) [reply subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractJavaGroovyIncrementalCompilationSupport.groovy:32]: This is test code, so it doesn't really matter, right?

Comment (asodja) [reply subprojects/language-java/src/integTest/groovy/org/gradle/java/compile/incremental/AbstractJavaGroovyIncrementalCompilationSupport.groovy:32]: It seems a lot of characters can be in Java class name. For example this compiles:
```
public class π {
}
```
:D 

So yeah, I would add them to this regex when needed.

**Comment by asodja** [comment]
@bot-gradle test and merge
