### ISSUE TITLE
Project.files(null) started failing in Gradle 9 RC1

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#34040]
### Current Behavior

Using the Kotlin DSL, starting in Gradle 9.0 RC1, this now fails:

```kts
// build.gradle.kts
val collection = files(null)
println("Collection: ${collection.from}")
```

with:

```

FAILURE: Build failed with an exception.

* Where:
Build file '/private/tmp/project3/build.gradle.kts' line: 2

* What went wrong:
Script compilation error:

  Line 1: val collection = files(null)
                                 ^ Argument type mismatch: actual type is 'Any?', but 'Any' was expected.

1 error
```

Up to Gradle 8.14, this worked fine:

```
> Configure project :
Collection: [null]

> Task :help
...
```

### Expected Behavior

This should continue to work in 9.0. 

### Context (optional)

It seems the adoption of JSpecify `NullMarked` at the package level.

### Self-contained Reproducer Project

See description.

### Gradle version

9.0 RC1

### Gradle version that used to work

8.14

**Comment by abstratt** [comment]
Duplicate of #34038
