### ISSUE TITLE
Configuration of maven-publish plugin fails with gradle 5.0 with NoClassDefFoundError : org.gradle.api.internal.ClosureBackedAction

### ISSUE THREAD

**Issue by thisisananth** [gradle/gradle#8026]
### Expected Behavior
Plugin should be configured and publishing should work without exception 
### Current Behavior
Running any task in the build with maven-publish fails with the exception java.lang.NoClassDefFoundError: org.gradle.api.internal.ClosureBackedAction

### Context
Builds are failing because of this. I'm seeing this only after upgrading to gradle 5.0. The build works fine in 4.10.3

### Steps to Reproduce (for bugs)
I have a multiproject build with 3 sub projects. In each subproject, I'm applying the maven-publish plugin. When I just run the build task, it is failing with the following exception 
17:13:45.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: org.gradle.api.internal.ClosureBackedAction
17:13:45.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$_apply_closure5.class$(DependencyManagementPlugin.groovy)
17:13:45.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$_apply_closure5.$get$$class$org$gradle$api$internal$ClosureBackedAction(DependencyManagementPlugin.groovy)
17:13:45.431 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at io.spring.gradle.dependencymanagement.DependencyManagementPlugin$_apply_closure5.doCall(DependencyManagementPlugin.groovy:116)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:105)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:166)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:239)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.ImmutableActionSet$SetWithManyActions.execute(ImmutableActionSet.java:329)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:250)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:239)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.pluginAdded(DefaultPluginContainer.java:49)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:180)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
17:13:45.432 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:130)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at build_ekqqg6q3f1vmrbrn2r422m9ql.run(C:\upgrade-ws\psf-sot-app\psf-log\build.gradle:16)
17:13:45.433 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
17:13:45.434 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 116 more

### Your Environment
Working Directory: C:\upgrade-ws\root-project\subproject-1
Gradle User Home: C:\Users\mm\.gradle
Gradle Distribution: Local installation at C:\Users\mm\AppData\Local\scoop\apps\gradle\5.0
Gradle Version: 5.0
Java Home: C:\Users\mm\AppData\Local\scoop\apps\oraclejdk\1.8.0-u92.wmc.1
JVM Arguments: None
Program Arguments: --warning-mode all --stacktrace --info --debug
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: bootJar
Windows 7

**Comment by marcphilipp** [comment]
Could you please provide a sample project to reproduce this issue?

**Comment by marcphilipp** [comment]
@noproxy Thanks!

**Comment by thisisananth** [comment]
@noproxy  Thanks. That fixed the problem!
