### ISSUE TITLE
Deprecations in user-space plugins

### ISSUE THREAD

**Issue by nedtwigg** [gradle/gradle#12462]
### Expected Behavior

As a plugin author, it's helpful to guide users through deprecations using the gradle deprecation system.  I have used this method to do that for a whilte

`org.gradle.util.SingleMessageLogger.nagUserOfReplacedPlugin(Ljava/lang/String;Ljava/lang/String;)V`

### Current Behavior

```
java.lang.NoSuchMethodError: org.gradle.util.SingleMessageLogger.nagUserOfReplacedPlugin(Ljava/lang/String;Ljava/lang/String;)V
```

### Context

It works in `6.1.1`, broken in `6.2.0`.  An example of an affected plugin is [here](https://github.com/diffplug/image-grinder/issues/5), but I have others.

"Don't use this API" is a perfectly reasonable answer, but userspace plugin authors have all the same migration issues that the Gradle platform does.  If this isn't the right way, can you point me to an issue where I can track when a userspace deprecation api will be available?

### Steps to Reproduce 

https://github.com/diffplug/image-grinder/issues/5

### Your Environment
N/A
