### ISSUE TITLE
Incremental java compilation fails when renaming classname with $ character

### ISSUE THREAD

**Issue by horseunnamed** [gradle/gradle#19257]
Issue occurs since Gradle 7.3. Tested with OpenJDK 11 and 13. Tiny reproduction sample is here: https://github.com/horseunnamed/Gradle-change-detection-issue  

### Expected Behavior
Incremental java compilation is successful when classname with $ is renamed (as it is with Gradle 7.2 and earlier versions) 

### Current Behavior
After changing java class name with $ character and running incremental build we get the error:
```
> Task :compileJava FAILED
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Input property 'stableSources' file .../src/main/java/issue/Class$Name.java has been removed.
  Input property 'stableSources' file .../src/main/java/issue/Main.java has changed.
  Input property 'stableSources' file .../src/main/java/issue/Class$NameChanged.java has been added.
Created classpath snapshot for incremental compilation in 0.0 secs.
Compiling with toolchain '/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home'.
Compiling with JDK Java compiler API.
.../src/main/java/issue/Main.java:5: error: cannot find symbol
        new Class$NameChanged();
            ^
  symbol:   class Class$NameChanged
  location: class Main
1 error
Incremental compilation of 3 classes completed in 0.012 secs.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.02 secs.

FAILURE: Build failed with an exception.
```

### Context
On our real world Android-project we had a very harmful impact from this issue when upgrading Gradle version to 7.3.1.
Incremental annotation processor in our project generates some files with dollar sign and this issue silently led us to `ClassNotFoundException` at runtime in some cases. 
It's very serious blocker for us to upgrade from 7.2.

### Steps to Reproduce 
Please see reproduction sample: https://github.com/horseunnamed/Gradle-change-detection-issue  

1. Run build task to compile java project with classname that conatins dollar sign (e.g. `Class$Name.java`) and reference to it somewhere else (from `Main.java` in my reproduction sample)
2. Change classname and reference to it with something that still contains dollar sign
3. Rerun build task
4. Get mentioned incremental compilation error

### Your Environment
Build scan of failed incremental build from reproduction sample: https://scans.gradle.com/s/b4qlo2umn7dms

**Comment by asodja** [comment]
@horseunnamed PR with the fix will be merged soon. Can you maybe share the name of the annotation processor? Is this some popular annotation processor in the Android world? 

We would like to find out how many users might be affected by this issue.

**Comment by horseunnamed** [comment]
@asodja, thanks for fixing this issue so quickly!
On real project we faced this issue with annotation processor from [Toothpick](https://github.com/stephanenicolas/toothpick) library.
I also have a [more complex reproducer](https://github.com/horseunnamed/Gradle-change-detection-issue/tree/real-world-case) with annotation processor from Toothpick. It's very close to our real project issue. See README from this sample for details.

**Comment by asodja** [comment]
Thank you for that info. Note that the fix is already on the latest nightly. Can you maybe try it and confirm that that fixes the issue? Here is the info how you can update the wrapper: https://gradle.org/nightly/

**Comment by horseunnamed** [comment]
I've tried to reproduce this issue on our real project with latest nightly build and can approve that issue was fixed :)
Thanks again!
