### ISSUE TITLE
Lombok Fails with Gradle v4.9 (working with Gradle v4.8)

### ISSUE THREAD

**Issue by aplatypus** [gradle/gradle#6059]
The Lombok annotation processor  get build error with **Gradle v4.9** after upgrading from Gradle v4.8, e.g.:

-  `lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.ClassCastException`

I didn't find any comments in the [4.9 release notes](https://docs.gradle.org/4.9/release-notes.html), so it seems to me that the fault lies with some change between  Gradle 4.8.1 (also works) and Gradle 4.8

### Expected Behaviour

A simple Java  build should work with Lombok (example below)

     gradle build 

With simple Java compile.

This small Java program compiles and run without problems using Gradle v4.8.  

### Current Behaviour

Witth **Gradle v4.9** working code fails with compilation errors after upgrading from Gradle v4.8:

-  `lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.ClassCastException`

This Error using Lombok with Gradle from a Linux command line.  I rolled back my project to a stable version of: Monday (today being Friday).  The build still failed with Gradle 4.9.  

### Context

A small java build is sufficient (see below).

Everything is the _same_ except the Gradle version, I backed out Gradle to Gradle v4.8 and ran the  build.

     gradle build 

-   That  **_works_**!!

### Steps to Reproduce (for bugs)

Sample  program
```
package app.cmd;

import lombok.extern.slf4j.Slf4j;
import org.apache.log4j.BasicConfigurator;
/**
 *  Main Class
 * 
 *    - lombok trail
 *
 *  @author aplatypus
 */
@Slf4j
public class LombokExample
{
   
    /**
     *  Main
     *
     *  @param args the command line arguments
     */
    public static void main(String... args)
    {
        try 
        {
            BasicConfigurator.configure();

            log.info("starting up");
        }
        catch( Exception  ex )
        {
            log.error("Exception within  runMain()... ", ex );
        }
            
    }

}//LombokExample main class
```

### Your Environment

```
O/S name:       Linux
Gradle version: 4.9 .... Fail
Gradle version: 4.8 .... GOOD 
Groovy version: 2.4.12
Java version:   1.8.0_172-b11 (vendor: Oracle Corporation)

Root project:   'root project 'foundation''
  JAVA_HOME   = '/usr/lib/java/jre/home'
  target...
    JRE_HOME  = '/usr/lib/java/jre/home'
    JDK_HOME  = '/usr/lib/java/jdk/home'

net.ltgt.apt = v0.17
Lombok       = v18.0
```

**Comment by oehme** [comment]
Duplicate of https://github.com/rzwitserloot/lombok/pull/1718
