### PR TITLE
Revert classpath ordering of distribution-loaded test framework classes

### LINKED ISSUE #24429: 8.1 RC 1: Regression in JUnit5 parameterized tests
### Current Behavior

Tests with `@ParameterizedTest` and `@MethodSource` no longer works, throwing
```
java.lang.NoSuchMethodError: 'java.lang.String[] org.junit.platform.commons.util.ReflectionUtils.parseQualifiedMethodName(java.lang.String)'
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.getFactoryMethodBySimpleOrQualifiedName(MethodArgumentsProvider.java:105)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.getFactoryMethod(MethodArgumentsProvider.java:69)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$provideArguments$0(MethodArgumentsProvider.java:54)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
...
```
during initialization.

### Context

It works in 8.0.2, not in 8.1-rc-1.

### Steps to Reproduce 

Run the attached project with `./gradlew test`.
[gradle-8.1-rc-1-parameterized-tests.tgz](https://github.com/gradle/gradle/files/11031418/gradle-8.1-rc-1-parameterized-tests.tgz)

### Your Environment

Build scan URL: https://scans.gradle.com/s/uzpq7lp7gox5e

### PR DESCRIPTION
**Pull request by jvandort**
When running embedded integration tests with test distribution, the junit-platform-launcher jar which is loaded from the gradle distribution is different than the version we usually test against. This version is incompatible with older versions of junit-platform-commons and junit-platform-engine jars pulled in by the corresponding junit jupiter versions.

To resolve this, we reversed the ordering of distribution loaded test framework jars to ensure our versions of these junit-platform-launcher dependencies came first on the classpath. This turned out to break the newest version of junit jupiter, which we do not test against, leading to a regression.

This reverses the order and ignores the embedded tests which break when testing against older versions of junit jupiter.

Fixes #24429

### CODE REVIEW

**Comment by jvandort** [comment]
@bot-gradle test this

**Review by big-guy — APPROVED** [review]

**Comment by jvandort** [comment]
@bot-gradle test and merge

**Review by ghale — APPROVED** [review]
