### ISSUE TITLE
Referencing classes in Gradle's API jar that are also in the JDK cause compilation errors in Eclipse when building with Java 9 and later

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#19577]
### Expected Behavior

A project that depends on Gradle's API jar should build cleanly in Eclipse when using Java 9+.

### Current Behavior

Compilation fails when trying to, for example, use code in `javax.xml.parsers` due to the package being split between the unnamed and `java.xml` modules.

### Context

The generated Gradle API jar contains packages and classes that are part of the JDK. These split packages cause compilation failures in Eclipse. It does not fail on the command line which, as per [this mailing list discussion](http://mail.openjdk.java.net/pipermail/jigsaw-dev/2018-December/014076.html), is due to [a bug](https://bugs.openjdk.java.net/browse/JDK-8215739) in the JDK. When the JDK bug is fixed, similar failures will occur with `javac`.

This problem prevents compilation of Spring Boot's `buildSrc` on its current main branch in Eclipse. Our `buildSrc` plugins use code in various `javax.xml` packages and it does not compile in Eclipse with Java 17.

IMO, Gradle's API jar should not contain classes and packages that are also part of the JDK.

### Steps to Reproduce

Import the project in [this zip file](https://github.com/gradle/gradle/files/7871062/java-xml-split-package.zip) into Eclipse. I'm using 2021-09 but I believe it'll occur in other versions of Eclipse as well. You should see two errors:

```
DocumentBuilderFactory cannot be resolved to a type	                                        Example.java	/java-xml-split-package/src/main/java/com/example	line 7	Java Problem
The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml	Example.java	/java-xml-split-package/src/main/java/com/example	line 3	Java Problem
```

### Your Environment

Build scan URL: scans.gradle.com is unavailable

I don't think this problem is environment-specific. FWIW, I'm using Eclipse 2021-09 on macOS with Temurin-17+35 (build 17+35).

**Comment by loetifuss** [comment]
Also having this issue. Our suite of Gradle plugins doesn't compile when imported with Eclipse Buildship and JDK 11. I can workaround this issue by limiting the module path of the Eclipse projects using the code below. The projects will compile now when "javax.xml" module is excluded. 
Unfortunately this doesn't really help since now my Mockito tests throw ClassNotFoundExceptions for "java.beans.IntrospectionException" which is contained in the "java.desktop" module. The "java.desktop" module can't be added since it has a dependency on "javax.xml".

Is there any way to get this working in Eclipse and JDK 11? It seems to be working in Intellij IDEA.

```
pluginManager.withPlugin('eclipse') {
	eclipse {
		classpath {
			file {
				whenMerged {
					def jre = entries.find { it.path.contains 'org.eclipse.jdt.launching.JRE_CONTAINER' }
					jre.entryAttributes['module'] = 'true'
					jre.entryAttributes['limit-modules'] = '<ENTER_DESIRED_MODULES'
				}
			}
		}
	}
}
```

**Comment by infosuitemka** [comment]
Also have same issue, after finally being able to lift project baseline to Java 11. Everywhere we have custom Gradle tasks present and thus have the gradle API jar in the compile classpath. As we use the xml APIs, the java.xml module is required.

**Comment by jskov-jyskebank-dk** [comment]
I see the same problem trying to work on Gradle plugins in Eclipse targeting java 17.

Fortunately, it is possible to work around. The below works for me with Gradle 8.2.1, java 17, and Eclipse 2023-03.

```groovy
// Workaround for https://github.com/gradle/gradle/issues/19577
//
// Makes a shaded copy of the gradle-api jar-file and switches the Eclipse classpath to use it.
// There is a per-root-project shaded file to allow for different shading configurations in different projects.
task makeShadedGradleApi(type: Zip) {
    def gradleVersion = project.gradle.gradleVersion
    def cacheDir = project.gradle.gradleUserHomeDir.toPath().resolve('caches').resolve(gradleVersion).resolve('generated-gradle-jars')
    def fileName = 'shaded-api-' + Integer.toHexString(project.rootDir.hashCode()) + '.jar'
    def shadedApiFile = cacheDir.resolve(fileName).toFile()
    def apiFile = cacheDir.resolve('gradle-api-' + gradleVersion + '.jar')

    archiveFile.set(shadedApiFile)
    from project.zipTree(apiFile)
    exclude "org/w3c/**/*"

    doFirst {
        logger.lifecycle("Shading $apiFile into $shadedApiFile")
    }
}

tasks.eclipseClasspath.dependsOn(makeShadedGradleApi)

eclipse {
    classpath {
        file {
            withXml {
                def cp = it.asNode()
                // Replace gradle-api library dependency with the shaded archive
                cp
                    .classpathentry
                    .findAll { e -> e.@kind == 'lib' && e.@path.contains('gradle-api') }
                    .each { e -> 
                        def c = e.clone()
                        c.@path = tasks.makeShadedGradleApi.archivePath

                        cp.remove(e)
                        cp.append(c)
                    }
            }
        }
    }
}
```

**Comment by infosuitemka** [comment]
I am out of the office until 31-07-2023.

Please contact InfoSuite support at ***@***.*** for assistance.


Note: This is an automated response to your message  "Re: [gradle/gradle] Referencing classes in Gradle's API jar that are also in the JDK cause compilation errors in Eclipse when building with Java 9 and later (Issue #19577)"( sent on 26-07-2023 13:41:00) . 

This is the only notification you will receive while this person is away.

**Comment by oleosterhagen** [comment]
The check for split packages can be disabled in the Eclipse compiler for Java:

1. Unzip `java-xml-split-package.zip`
2. Import this Gradle project: _File > Import... > Gradle / Existing Gradle Project > ..._
3. Open the generated file `java-xml-split-package/.settings/org.eclipse.jdt.core.prefs`
4. Add `org.eclipse.jdt.core.compiler.ignoreUnnamedModuleForSplitPackage=enabled`
5. After saving the file the error should disappear. Otherwise try, right-click on the project: _Gradle > Refresh Gradle Project_

This feature has been introduced with https://github.com/eclipse-jdt/eclipse.jdt.core/pull/424. Unfortunately there is still no option in the UI for this.

**Comment by lkasso** [comment]
Apologies for the delayed response.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by glitch8eda** [comment]
> The check for split packages can be disabled in the Eclipse compiler for Java:
> 
>     1. Unzip `java-xml-split-package.zip`
> 
>     2. Import this Gradle project: _File > Import... > Gradle / Existing Gradle Project > ..._
> 
>     3. Open the generated file `java-xml-split-package/.settings/org.eclipse.jdt.core.prefs`
> 
>     4. Add `org.eclipse.jdt.core.compiler.ignoreUnnamedModuleForSplitPackage=enabled`
> 
>     5. After saving the file the error should disappear. Otherwise try, right-click on the project: _Gradle > Refresh Gradle Project_
> 
> 
> This feature has been introduced with [eclipse-jdt/eclipse.jdt.core#424](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/424). Unfortunately there is still no option in the UI for this.

While this might allow the project to run (I have not tried it), it does not fix the problem which is that, through gradle-api dependency, the user is forced to add another JDK to the classpath independently of the project's JDK.  Gradle-api should be configured to use a "runtime" dependency to the JDK so that the user's JDK can be picked up at runtime.

**Comment by eskatos** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

****
With Gradle >= 9.0.0 requiring Java 17 to run and Java 8 for worker processes, all runtimes in use will have the `javax.xml` package built in. We should now be able to safely remove it from the Gradle API JAR.

Related
* https://github.com/gradle/gradle/issues/29483
* https://github.com/gradle/gradle/issues/16147

**Comment by jskov-jyskebank-dk** [comment]
The gradle-api-9.0.0.jar still includes the org.w3c.dom package, which conflicts with the JDK jdk.xml module.

**Comment by eskatos** [comment]
@jskov-jyskebank-dk this was shipped in Gradle 9.1.0

**Comment by jskov-jyskebank-dk** [comment]
Cool, ta!
