### ISSUE TITLE
NowInAndroid project is not building with current `master` branch 

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#26462]
### Current Behavior

[NowInAndroid](https://github.com/android/nowinandroid) doesn't build with latest Gradle (`master` branch).
It does however build with Gradle `8.4-rc-1`, so we just recently broke it on `master`.

### Expected Behavior

[NowInAndroid](https://github.com/android/nowinandroid) should build with latest Gradle.

### Context (optional)

I discovered this when trying to set up performance tests based on this project for Gradle.

The failure is somewhat a blocker for this effort, but I think I can work around it, if need be.

### Steps to Reproduce

Run the `assembleDebug` task on [NowInAndroid](https://github.com/android/nowinandroid) (commit `e40fb7925deac9912985522378281ce0f6c9d31a`, latest `main` branch at the moment), it results in the failure of the `:app:demoDebugOssDependencyTask` task:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/component/AmbiguousVariantSelectionException
	at com.google.android.gms.oss.licenses.plugin.DependencyTask.loadArtifactInfo(DependencyTask.groovy:64)
	at com.google.android.gms.oss.licenses.plugin.DependencyTask.action(DependencyTask.groovy:51)
```

### Gradle version

8.5-20230921121928+0000

### Gradle version that used to work

8.4-rc-1

**Comment by eskatos** [comment]
The breakage was introduced in https://github.com/gradle/gradle/commit/14f1d303d3b853d4090bbd704b56ad2b46c54ef7 from
* https://github.com/gradle/gradle/pull/26199
