### ISSUE TITLE
Incremental annotation processing does not find dependent classes with `proc:only`

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#17802]
When doing incremental annotation processing with `proc:only`, compilation may fail because of some missing classes.

For example when you have a class `MyImmutable` which depends on `SupportType`, and then you only change `MyImmutable`, then `SupportType` is not passed to the Java compiler by incremental annotation processing, so it fails:

```
gradle-7.1-inc-annotation-processing/src/main/java/mypkg/MyImmutable.java:23: error: cannot find symbol
   SupportType supportType();
```

This did break in Gradle 7.1, and works with Gradle 7.0.

Here is a reproducer with instructions in its `README.md`: 

[gradle-7.1-inc-annotation-processing.zip](https://github.com/gradle/gradle/files/6860916/gradle-7.1-inc-annotation-processing.zip)

---
cc: @gradle/execution

**Comment by wolfs** [comment]
@oehme Can you take a look at this bug?

**Comment by oehme** [comment]
Yep, will do.

**Comment by oehme** [comment]
> SupportType is not passed to the Java compiler by incremental annotation processing

That's expected and unrelated to annotation processing. `SupportType` is not affected by changes to `MyImmutable`, so why would we recompile it? The classes dir is added to the compile classpath by the incremental compiler, so that previously compiled, unaffected classes are visible.

This example project uses a separate folder for just the classes created by annotation processing. As such, none of the unaffected source types are visible. I wonder why a project would be set up like this? It's creating strictly more work than doing everything in one go.

**Comment by ldaley** [comment]
> It's creating strictly more work than doing everything in one go.

In the case where I discovered this, it is to work around bugs in the annotation processors that result in uncompilable code being produced. I've just found a workaround with `--sourcepath` and `--implicit:none` that allows us to keep things separated and use incremental processing with a small cost.  If we were to disable incremental processing with `proc:only` this will break.

A secondary reason is to support a cheaper `generateSource` task that generates all the source needed for effective working in an IDE.

**Comment by oehme** [comment]
>  If we were to disable incremental processing with proc:only this will break.

It was never incremental, all versions up to Gradle 7.0 did a full recompile (for the wrong reason, but still). So we'd just return to how it was before.

**Comment by ldaley** [comment]
> How does doing it in two steps fix that?

The generated source can be text patched before being being compiled.

**Comment by ldaley** [comment]
> Do you have some numbers for this? 

No I don't.

**Comment by oehme** [comment]
Got it. Still, given that this was non-incremental for every release except the bug in 7.0, I'd stick with the plan to do a full recompile with `proc:only`.

**Comment by wolfs** [comment]
@oehme @ldaley Can we close this issue now?

**Comment by ldaley** [comment]
@wolfs yes, this can be closed.
