### ISSUE TITLE
`com.gradle.plugin-publish` compilation issue upon upgrading to Gradle 8.0.2

### ISSUE THREAD

**Issue by big-andy-coates** [gradle/gradle#24458]
Gradle based projects that that make use of the `com.gradle.plugin-publish` plugin to publish Gradle plugins, and which define a `pluginBundle` block, don't compile after upgrading from Gradle 7.5.1 to 8.0.2.

I've created a simple Github repo to demonstrate this. See https://github.com/big-andy-coates/gradle-8-plugin-issue.

The repo:
 1. uses `gradle init` to bootstrap a Gradle 7.5.1 based Gradle plugin project, 
 2. applies the `com.gradle.plugin-publish`, 
 3. defines a `pluginBundle` block,
 4. upgrades Gradle to 8.0.2,

### Expected Behavior

Project still builds

### Current Behavior

Build fails with the error:

```
> Configure project :plugin
e: /Users/andy/dev/github.com/big-andy-coates/gradle-8-plugin-issue/plugin/build.gradle.kts:58:1: Unresolved reference: pluginBundle
e: /Users/andy/dev/github.com/big-andy-coates/gradle-8-plugin-issue/plugin/build.gradle.kts:59:5: Unresolved reference: website
e: /Users/andy/dev/github.com/big-andy-coates/gradle-8-plugin-issue/plugin/build.gradle.kts:60:5: Unresolved reference: vcsUrl
e: /Users/andy/dev/github.com/big-andy-coates/gradle-8-plugin-issue/plugin/build.gradle.kts:62:5: Unresolved reference: tags

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/andy/dev/github.com/big-andy-coates/gradle-8-plugin-issue/plugin/build.gradle.kts' line: 58

* What went wrong:
Script compilation errors:

  Line 58: pluginBundle {
           ^ Unresolved reference: pluginBundle

  Line 59:     website = "https://www.creekservice.org/${rootProject.name}/"
               ^ Unresolved reference: website

  Line 60:     vcsUrl = "https://github.com/creek-service/${rootProject.name}"
               ^ Unresolved reference: vcsUrl

  Line 62:     tags = listOf("creek", "creekservice")
               ^ Unresolved reference: tags

4 errors

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### Context

Trying to update project to latest Gradle version is failing...

### Steps to Reproduce 

See https://github.com/big-andy-coates/gradle-8-plugin-issue.

### Your Environment

Running on Mac with M1 chip, which I know can cause problems, but in this case build also fails on GitHub Ubuntu-latest runners too.

Build scan URL: https://scans.gradle.com/s/z4jyeehami2io

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

This is the intended behavior and there’s no plan to change it. This issue will be closed.

***

`pluginBundle` was removed it Gradle 8.0+ with a new version pluginPublish. Unfortunately, we did not publish information about it properly. 

***
This is a valid documentation issue which we will address.

**Comment by big-andy-coates** [comment]
Thanks!

Updating `pluginBundle` to `gradlePlugin`...

**Comment by unredundant** [comment]
hi... can we get a link here to the proper documentation? I'm running into the same issue, and it's not clear what devs are supposed to do.  for example, 

> Updating pluginBundle to gradlePlugin...

the `gradlePlugin` extension has no `tags` field.  so i'm guessing this isn't the only thing we need to change?

**Comment by ov7a** [comment]
@unredundant The exact change about the removal is [here](https://docs.gradle.org/current/userguide/upgrading_version_7.html#pluginbundle_dropped_in_plugin_publish_plugin). This section has also all required links to [the updated documentation.](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#configure_the_plugin_publishing_plugin)
