### ISSUE TITLE
Gradle 4.1/4.2 cannot build lombok-processor required code with JDK 9

### ISSUE THREAD

**Issue by hltj** [gradle/gradle#3012]
### Expected Behavior

Should work as Gradle 3.5 to 4.0.2 when building lombok-processor required code with JDK 9.

### Current Behavior

Fail to build lombok-processor required code with JDK 9 using Gradle 4.1/4.2, while the Gradle 3.5 to 4.0.2 works fine.
Here is a example output of failure during building my demonstration project https://github.com/hltj/java9demo/tree/master/lombok :
```
> Task :compileJava
/home/hltj/java9demo/lombok/src/main/java/me/hltj/java9demo/lombok/LombokDemo.java:8: warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.IllegalArgumentException: com.sun.tools.javac.api.ClientCodeWrapper$WrappedStandardJavaFileManager extends com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager implements javax.tools.StandardJavaFileManager
class Language {
^
        at lombok.javac.apt.LombokFileObjects.getCompiler(LombokFileObjects.java:130)
        at lombok.javac.apt.InterceptingJavaFileManager.<init>(InterceptingJavaFileManager.java:40)
        at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:164)
        at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:85)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:69)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:675)
        ...
        ... (full information can be found in scan log)
        ...
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
/home/hltj/java9demo/lombok/src/main/java/me/hltj/java9demo/lombok/LombokDemo.java:17: error: incompatible types: int cannot be converted to val
        val version = Integer.parseInt(System.getProperty("java.version"));
                                      ^
/home/hltj/java9demo/lombok/src/main/java/me/hltj/java9demo/lombok/LombokDemo.java:19: error: constructor Language in class Language cannot be applied to given types;
        val java = new Language("Java", version);
                   ^
  required: no arguments
  found: String,val
  reason: actual and formal argument lists differ in length
/home/hltj/java9demo/lombok/src/main/java/me/hltj/java9demo/lombok/LombokDemo.java:21: error: cannot find symbol
        log.info("Hello Lombok in {}.", java);
        ^
  symbol:   variable log
  location: class LombokDemo
3 errors
1 warning
```

### Context

As described in other sections.

### Steps to Reproduce (for bugs)

``` bash
git clone https://github.com/hltj/java9demo.git
cd java9demo/lombok/
./gradlew build # works fine with Gradle 4.0.2
./gradlew clean
./gradlew wrapper --gradle-version=4.2 --distribution-type=bin
./gradlew build # failed with Gradle 4.2
```

### Your Environment

```
./gradlew -v
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/hltj/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7/gradle-4.2/lib/groovy-all-2.4.11.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9 (Oracle Corporation 9+181)
OS:           Linux 3.10.0-229.el7.x86_64 amd64
```

 * Build scan URL: https://scans.gradle.com/s/izpc2gsgfjd6m

**Comment by oehme** [comment]
This probably happens because we have a custom file manager on Java 9 and lombok tries to access file manager internals. Maybe we can adjust our file manager so the lombok hacks work again. Or lombok can add a specific hack for Gradle.

Cc @eljobe since you worked on this.

**Comment by thetric** [comment]
Any updates on this issue?

**Comment by thetric** [comment]
@hltj @oehme This issue seems to be fixed in an Edge release of Lombok. See PR https://github.com/rzwitserloot/lombok/pull/1495, issues: https://github.com/rzwitserloot/lombok/issues/1472#issuecomment-339578781, https://github.com/rzwitserloot/lombok/issues/1435#issuecomment-339579066

**Comment by rspilker** [comment]
I've created a [docker setup](https://github.com/rzwitserloot/lombok/tree/master/docker) to reproduce gradle problems and test fixes.

I can reproduce the bug with 1.16.18, but no longer with the edge release.

**Comment by bmuschko** [comment]
@hltj Sounds like the issue has been fixed with the Edge release. I am going to close this issue for now. Please let us know if you still have issues.

**Comment by hltj** [comment]
@thetric @bmuschko It works with edge release of lombok! Thanks a lot.
