### ISSUE TITLE
Scala plugin introduces configurations that have unresolvable dependencies

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#6854]
See related discussions https://github.com/gradle/gradle/issues/6750#issuecomment-422989736

### Expected Behavior

`gradle dependencies` will not report failed dependencies unless there actually are failed dependencies.

### Current Behavior

`gradle dependencies` with the `scala` plugin applied creates "incremental analysis" configurations that report all dependencies as "FAILED".

Beyond the dependencies report, plugins/tasks that attempt to resolve all configurations in a project will now fail.

I think this has some impact on dependency locking as well.

### Context

The incremental analysis configurations created by the Scala plugin are for resolving incremental Scala compilation artifacts from other projects.  This requires using an artifact view to filter out dependencies that do not expose this information (external dependencies or Java projects).  The dependencies report and other tasks that resolve configurations do not have access to that.

As a workaround (this is temporary until this issue is closed):
```
configurations.all {
    if (name.startsWith("incrementalScalaAnalysis")) {
        extendsFrom = []
    }
}
```

### Steps to Reproduce (for bugs)

Given a build:
```
project(":java") {
    apply plugin: 'java'
}
project(":scala") {
    apply plugin: 'scala'
    dependencies {
        compile(project(":java"))
    }
}
```

Running `gradle scala:dependencies` will report failed dependencies in the "incremental analysis" configurations.

**Comment by ljacomet** [comment]
@big-guy Is this something that should be fixed in a `4.10.x`?

**Comment by big-guy** [comment]
I'm not sure. It's certainly ugly behavior.  I guess the bigger question is if the Scala plugin is doing the right thing, or if we should be able to handle this in a different way that doesn't expose a "unresolvable" configuration.

**Comment by felipecsl** [comment]
We started seeing Scala compilation errors after upgrading to 5.0-rc-1 for projects that used to work with v4.10. This seems related but the workaround doesn't seem to fix it. It just doesn't seem to be able to resolve some dependencies that previously worked. Any ideas?

**Comment by big-guy** [comment]
This wouldn't cause dependency failures.  Could you open a new issue @felipecsl with some more details?

**Comment by ljacomet** [comment]
Decided that nothing was to be done with this for `4.10`. Will be looked at in the future in a `5.x` release.

**Comment by dsilvasc** [comment]
@big-guy by the way, per [recent api changes](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) should that be `configurations.all` or `configurations.configureEach`?

**Comment by big-guy** [comment]
For now, `configurations.all` is what we'd recommend because `configurations.configureEach` won't make a difference.  The task configuration avoidance only focuses on tasks, but there's some shared infrastructure/APIs.  Other containers need to be eagerly/fully realized still.

**Comment by dsilvasc** [comment]
@ljacomet did 5.x or 6.x resolve this?

**Comment by blaskowski94** [comment]
Still seeing this issue with 6.3

**Comment by chetanmeh** [comment]
This issue causes issues with Spring Boot Gradle plugin also with Gradle 6.3

**Comment by geirsandearm** [comment]
Still seeing this issue with 6.7

**Comment by monosoul** [comment]
Still there in 6.8.3

**Comment by noahmonster** [comment]
Here's the same workaround, but for Kotlin based build files.

```
configurations.all {
    if (name.startsWith("incrementalScalaAnalysis")) {
        setExtendsFrom(emptyList())
    }
}
```

**Comment by sschuberth** [comment]
@big-guy is there a way to raise the priority of this? The problem sounds like it should be fixable in not too much time by an experienced Gradle developer.

**Comment by rmartine-ias** [comment]
If it saves anyone else a bit of time, here's something that works in an init script, to fix this issue for cyclonedx:
(Hoping the keywords get picked up by the indexing bots :P)

```gradle
initscript {
    dependencies {
        // Later versions (1.5.0+) do not work with gradle 2.3.
        classpath 'org.cyclonedx:cyclonedx-gradle-plugin:1.4.0'
    }
}
rootProject {
    // Not using plugins DSL because it does not work in initscripts.
    apply plugin: org.cyclonedx.gradle.CycloneDxPlugin

    // Fixes: https://github.com/gradle/gradle/issues/6854
    cyclonedxBom {
        skipConfigs += ["incrementalScalaAnalysisFortest", "incrementalScalaAnalysisFormain"]
    }
}

**Comment by rmartine-ias** [comment]
See also: https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/188

**Comment by oriy** [comment]
@big-guy I think this is resolved when using zinc `1.10.2`

using `gradle 8.6`
```
scala {
    zincVersion.set("1.10.2")
}
```

**Comment by big-guy** [comment]
This was fixed in 9.0.0: https://github.com/gradle/gradle/pull/32547

**Comment by sschuberth** [comment]
> This was fixed in 9.0.0: [#32547](https://github.com/gradle/gradle/pull/32547)

Then I guess it's wrong that the bot added it to the 9.6.0 RC1 milestone?

**Comment by big-guy** [comment]
> > This was fixed in 9.0.0: [#32547](https://github.com/gradle/gradle/pull/32547)
> 
> Then I guess it's wrong that the bot added it to the 9.6.0 RC1 milestone?

Thanks!

Bad bot. cc @gradle/bt-developer-productivity
