### ISSUE TITLE
Support Java 19

### ISSUE THREAD

**Issue by famod** [gradle/gradle#20372]
### Expected Behavior
Java 19 compilation target is supported.

### Current Behavior
```
[INFO] --- exec-maven-plugin:3.0.0:exec (gradle) @ quarkus-gradle-model ---

FAILURE: Build failed with an exception.

* Where:
Settings file '/home/runner/work/quarkus/quarkus/devtools/gradle/settings.gradle'

* What went wrong:
Could not compile settings file '/home/runner/work/quarkus/quarkus/devtools/gradle/settings.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 63
  
  java.lang.IllegalArgumentException: Unsupported class file major version 63
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
  	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
  	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
  	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
  	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:57)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:44)
  	at org.codehaus.groovy.ast.decompiled.TypeSignatureParser.visitEnd(TypeSignatureParser.java:110)
  	at groovyjarjarasm.asm.signature.SignatureReader.parseType(SignatureReader.java:206)
  	at groovyjarjarasm.asm.signature.SignatureReader.accept(SignatureReader.java:124)
  	at org.codehaus.groovy.ast.decompiled.ClassSignatureParser.parseClassSignature(ClassSignatureParser.java:74)
  	at org.codehaus.groovy.ast.decompiled.ClassSignatureParser.configureClass(ClassSignatureParser.java:32)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitSupers(DecompiledClassNode.java:185)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.isUsingGenerics(DecompiledClassNode.java:86)
  	at org.codehaus.groovy.ast.tools.GenericsUtils.nonGeneric(GenericsUtils.java:275)
  	at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:101)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lambda$createMethodNode$1(DecompiledClassNode.java:230)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.createMethodNode(DecompiledClassNode.java:236)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:203)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:122)
  	at org.codehaus.groovy.ast.ClassNode.tryFindPossibleMethod(ClassNode.java:1283)
  	at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:251)
  	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:133)
  	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:108)
  	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
  	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
  	at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:108)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructor(ClassCodeVisitorSupport.java:101)
  	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1089)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
  	at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$3(CompilationUnit.java:209)
  	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:942)
  	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
  	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
  	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
  	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
  	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
  	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
  	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
  	at org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler.compileScript(DefaultScriptCompilationHandler.java:139)
        [...]
```

### Context

Over at Quarkus we have a nighly build that's running with the current EA JDK, which is 19 since 18 switched to GA in March.
Apart from that, there will be users wanting to fully run on Java 19 once it reaches GA.

ASM 9.3 with Java 19 support was released yesterday: https://asm.ow2.io/versions.html

**Comment by jesperancinha** [comment]
Hi there, I'm running into this same issue since yesterday and I need this to run tests on Project Loom(JDK 19) using gradle, and I'm not interested in using Maven at the moment for this. Is there a way to use some sort of trick or some sort of EA, RC release to this running? Further, I'm noticing that gradle 7.4.2 seems to work with this JDK 19 on a MAC, but I'm guessing this is not expected? Anyways, I made a github action to install JDK 19 and this action is using linux and that then it all seems to fail when the build runs. The Exception I get is exactly the same as reported here and I've already checked the PATH and the JAVA_HOME and it's all ok.

**Comment by marcphilipp** [comment]
@jesperancinha Have you tried using https://docs.gradle.org/current/userguide/toolchains.html?

**Comment by jesperancinha** [comment]
@marcphilipp , I moved on in the meantime with maven. I just tried it with the toolchain like this:

```gradle
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(19)
    }
}
```

And I still get the same exception. 
This is what I get with `java -version`:

```shell
openjdk version "19-loom" 2022-09-20
OpenJDK Runtime Environment (build 19-loom+6-625)
OpenJDK 64-Bit Server VM (build 19-loom+6-625, mixed mode, sharing)
```

And this with `gradle -version`

```shell
------------------------------------------------------------
Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          19-loom (Oracle Corporation 19-loom+6-625)
OS:           Mac OS X 12.3.1 x86_64
```

Any command that I run including `gradle wrapper --gradle-version 7.4.2` doesn't seem to work as well. I am using a sub-module structure. I'm not sure if this has any influence to this. I can move on with Maven anyways, but that wasn't my initial intention. This maybe also a bit too soon for this. I see in Gradle [compatibility matric](https://docs.gradle.org/current/userguide/compatibility.html) that Gradle offers compatibility up to JDK 17. I just found it odd that it did work in some occasions but it could be that I ended up compiling with GraalVm for JDK 17 and then ran it with the JRE in the JDK19.

**Comment by marcphilipp** [comment]
You need to use a supported version of Java to run Gradle (e.g. Java 17), i.e. `gradle -version` should print that version. If you use toolchains, Gradle will then use a different version for all compile tasks.

**Comment by jesperancinha** [comment]
Indeed @xor-freenet .I run my project with JDK 19, not only to test the JDK but also to see how Project Loom works. And just for clarity, it is not my intention to build my project with gradle under a JDK 17 environment, which seems to be @marcphilipp ‘s  interpretation. Anyways, altough I very much like gradle, I had no choice but to convert the initial setup to maven, because maven does work for this and gradle afaik not yet.

**Comment by marcphilipp** [comment]
@xor-freenet @jesperancinha We do exactly that for the [JUnit 5 build on GitHub Actions](https://github.com/junit-team/junit5/blob/main/.github/workflows/cross-version.yml). It requires installing two JDKs: one for running Gradle (we use JDK 17) and one for running the tests which is then passed to the build: https://github.com/junit-team/junit5/blob/9d23af35eda6fc079c6019f5a58a4245db537d6f/.github/workflows/cross-version.yml#L45

That project property is then read and used to configure Gradle to use that JDK for compilation and test execution here: https://github.com/junit-team/junit5/blob/9d23af35eda6fc079c6019f5a58a4245db537d6f/buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts

While a bit more effort to set up, it completely decouples the two things and avoids having to deal Gradle not yet being compatible when a new EA releases comes out.

That being said, JDK 19 support is of course coming to Gradle. @gradle/bt-support It's currently slated for 7.6, correct?

**Comment by demidko** [comment]
> Indeed @xor-freenet .I run my project with JDK 19, not only to test the JDK but also to see how Project Loom works. And just for clarity, it is not my intention to build my project with gradle under a JDK 17 environment, which seems to be @marcphilipp ‘s interpretation. Anyways, altough I very much like gradle, I had no choice but to convert the initial setup to maven, because maven does work for this and gradle afaik not yet.

How did you manage to run maven with jdk 19? May I have a look?

**Comment by jesperancinha** [comment]
Hi @demidko, the only thing I did that was a bit different than what I normally do is having the JDK 19 installed manually. In maven, I just set up the version to `19` and in the command line or Intellij I just made sure to have it in some folder downloaded and unzipped and the JAVA_HOME correctly set up. I made some scripts to achieve this here: https://github.com/jesperancinha/good-story/blob/main/Makefile. But anyways, if you want to have a look at a running example of this I made two projects about this. One working example with the JDK19 here: https://github.com/jesperancinha/good-story and another, which is a GitHub action that I am using in the same project here: https://github.com/JEsperancinhaOrg/loom-action. Feel free to have a look at them.

**Comment by aseemsavio** [comment]
Is there a roadmap available for when we get to have support for JDK 19? If someone could share, that would be awesome!

**Comment by big-guy** [comment]
Testing with the latest 7.6 with Java 19, everything appears to be working:
[builds.gradle.org/viewLog.html?buildId=54959159&buildTypeId=Gradle_Experimental_Check_Stage_ReadyforNightly_Trigger](https://builds.gradle.org/viewLog.html?buildId=54959159&buildTypeId=Gradle_Experimental_Check_Stage_ReadyforNightly_Trigger)

what's left to do:
- Update compatibility.adoc to say Gradle can run with JDK19
- Add something to release-features.txt
- Add something to release notes
- Update CI configuration to allow tests to run with JDK19 on master/release
- Look at the current matrix of test coverage on master/release and figure out where we add JDK19 coverage

We cannot call this done without us running some tests with JDK19 as part of the release pipeline.

**Comment by demidko** [comment]
@jesperancinha Thank you, your example helped test Project Loom in our project

**Comment by ice1000** [comment]
Java 19 GA is coming in 4 days!!

**Comment by Jire** [comment]
Java 19 is now out, has this been addressed yet?

**Comment by octylFractal** [comment]
https://github.com/gradle/gradle/pull/21721 fixed all known issues. No release has been made with this yet.

CI coverage is still not complete, as indicated by https://github.com/gradle/gradle/issues/20372#issuecomment-1215170433

**Comment by ice1000** [comment]
Cool!!

**Comment by ljacomet** [comment]
Yes, the [release nightlies](https://gradle.org/release-nightly/)

**Comment by ps-89** [comment]
Curious, when will Gradle v7.6 be released?

**Comment by eskatos** [comment]
@ps-89 when it is ready :)

You can check the GitHub milestone for 7.6-RC1 here
https://github.com/gradle/gradle/milestones/7.6%20RC1

**Comment by dbwiddis** [comment]
> Yes, the [release nightlies](https://gradle.org/release-nightly/)

Updating my wrapper to use a nightly build sounds great, except...

This `release-nightly` link currently is showing `6.9.3-20221007060817+0000` as the latest, but my build is incompatible with Gradle < 7.x.

The `nightly` link [here](https://gradle.org/nightly/) is showing `8.0-20221007221152+0000`, but my build is incompatible with Gradle > 7.x.

The `release candidates` link [here](https://gradle.org/release-candidate/) is showing `7.5-rc-5`.

JDK 19 has been GA for 17 days.  I updated my mac to openjdk 19 using homebrew and reverting to 18.x isn't easily possible. I can use 17, but I need JDK 18+ features.

Any suggestions on how I can get a JDK-19-compatible gradle 7.x "release" to use with my gradle wrapper?  I'm totally blocked here.

**Comment by ice1000** [comment]
@dbwiddis see gradle/wrapper/gradle-wrapper.properties

**Comment by ice1000** [comment]
@dbwiddis 
```properties
distributionUrl=https\://services.gradle.org/distributions-snapshots/gradle-7.6-20220920234319+0000-bin.zip
```

**Comment by octylFractal** [comment]
Also remember that you do not necessarily need to use a nightly to _compile with 19_, it is only needed to run the Gradle daemon itself with Java 19 and update the default tool versions to 19-compatible versions. If you have a plain Java project, using [toolchains](https://docs.gradle.org/current/userguide/toolchains.html) to compile with Java 19 works in Gradle 7.5.1. Other projects may also work on a case-by-case basis.

**Comment by ice1000** [comment]
From now on, checking the status of Gradle 7.6 RC1 will be the first thing I do after waking up in the morning

**Comment by dbwiddis** [comment]
> Also remember that you do not necessarily need to ...

I made a brief attempt to follow your link and understand what you said, but the practical matter is that I know whatever time I spend is going to be wasted and I want to do the minimum amount possible to get back to work until the official (and fully CI-covered!) release is out.  One-liner changes to config files or command-line updates are awesome and acceptable workarounds.  Changing a build system for a project on which I'm not a maintainer is not.

**Comment by DanielThomas** [comment]
The originally reported Groovy compilation error is dependent on the Groovy version on the classpath, so 7.6 will not help you there. For that you need at least Groovy 3.0.11 (because you need ASM 9.3 - https://issues.apache.org/jira/browse/GROOVY-10569) and 4.0.2 if you need to set a JDK 19 target (https://issues.apache.org/jira/browse/GROOVY-10573).

**Comment by GavinRay97** [comment]
@ice1000 

https://docs.gradle.org/7.6-milestone-1/release-notes.html
https://docs.gradle.org/8.0-milestone-2/release-notes.html

**Comment by ice1000** [comment]
> @ice1000 
> 
> https://docs.gradle.org/7.6-milestone-1/release-notes.html
> https://docs.gradle.org/8.0-milestone-2/release-notes.html
> 
> 🥳 

Thank you! I can finally sleep

**Comment by ice1000** [comment]
```
> ./gradlew wrapper --gradle-version=7.6-milestone-1
Downloading https://services.gradle.org/distributions-snapshots/gradle-7.6-milestone-1-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-7.6-milestone-1-bin.zip
```

**Comment by ice1000** [comment]
😭

**Comment by GavinRay97** [comment]
You have to remove `snapshots` from the URL, for example:
-  https:\//services.gradle.org/distributions/gradle-8.0-milestone-2-bin.zip

**Comment by dbwiddis** [comment]
That line is verbatim from https://docs.gradle.org/7.6-milestone-1/release-notes.html

**Comment by ljacomet** [comment]
@ice1000 Can you file an issue for this?
It looks like our snapshot / non-snapshot logic is flawed in the wrapper task and does the wrong thing for milestones.

**Comment by leotm** [comment]
> You have to remove `snapshots` from the URL, for example:
> 
> * `https:\//services.gradle.org/distributions/gradle-8.0-milestone-2-bin.zip`

Exactly [right](https://github.com/leotm/react-native-template-new-architecture/issues/1093) 👌 (what i' did testing React Native) and full/latest list [here](https://services.gradle.org/distributions)

**Comment by LeoFuso** [comment]
> ```
> > ./gradlew wrapper --gradle-version=7.6-milestone-1
> Downloading https://services.gradle.org/distributions-snapshots/gradle-7.6-milestone-1-bin.zip
> 
> Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle-dn.com/distributions-snapshots/gradle-7.6-milestone-1-bin.zip
> ```

This is strange, I just downloaded the 7.6 version, here's my `gradle-wrapper.properties` 

```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-milestone-1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by angryziber** [comment]
How come a Java 19 compatible Gradle is still not available as a stable version two months after Java 19 release?

Maybe it should be considered how to make Gradle more future-proof, so it would run with any future Java version, like all normal Java apps do?

**Comment by ice1000** [comment]
> How come a Java 19 compatible Gradle is still not available as a stable version two months after Java 19 release?
> 
> Maybe it should be considered how to make Gradle more future-proof, so it would run with any future Java version, like all normal Java apps do?

They need to update asm & groovy. This is not Gradle's fault.

However, I still think there's something wrong that makes asm & groovy not being more future-proof.

**Comment by MartinX3** [comment]
I hope they'll switch to kotlin as long-term goal.

**Comment by d9j** [comment]
Just use maven ..unless you beleive the features gradle offers  actually are needed.  maven always have first class java building support

**Comment by martinbonnin** [comment]
Gradle 7.6 is out with support for building and running code with Java 19: https://docs.gradle.org/7.6/release-notes.html

**Comment by octylFractal** [comment]
> However, I still think there's something wrong that makes asm & groovy not being more future-proof.

Hopefully, [this draft JEP](https://openjdk.org/jeps/8280389) is accepted and will provide automatic upgrades in the future, so this should eventually be resolved.

Another possibility is that Groovy could stop bundling ASM, though I imagine they do that for a good reason.

**Comment by rabee-abu-michael** [comment]
welcome everybody
I am facing this problem, is there a solution?
![5](https://user-images.githubusercontent.com/100477396/211622834-dfc6f1da-f080-4ef6-a568-e4104cb9889a.PNG)

**Comment by jershell** [comment]
> welcome everybody I am facing this problem, is there a solution? ![5](https://user-images.githubusercontent.com/100477396/211622834-dfc6f1da-f080-4ef6-a568-e4104cb9889a.PNG)

Do you can up a gradle version to 7.6? From your stacktrace i suggest you have gradle 7.4

**Comment by donat** [comment]
@jershell @rabee-abu-michael Judging from the screenshot you use VSCode. By default, the Java/Gradle integration will use the same JDK for Gradle as the Java tooling backend (Java 19 in this case).  According to the [documentation](https://github.com/microsoft/vscode-gradle#java-specific-settings), you can define a separate JDK for Gradle by configuring `java.import.gradle.java.home`.
