### ISSUE TITLE
Gradle 5.4.x fails to build using Java 12

### ISSUE THREAD

**Issue by rianlowrey** [gradle/gradle#9161]
Attempting to execute a gradle build using release v5.4.0 fails with the following:

```./gradlew clean install -Pgradle_installPath=/tmp/bld/gradle/gradle-5.4.0-out2
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :cli:compileJava FAILED
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.

> Task :baseServices:compileJava FAILED
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.

> Task :docs:dslMetaData
Parsed 1557 classes in 3.364 seconds

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':cli:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':baseServices:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4-rc-1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 31s
122 actionable tasks: 108 executed, 14 up-to-date
```

### Expected Behavior
Build completes on all supported platforms and versions of underlying jvm executing the build.

### Current Behavior
Build fails stating "error: [Source|Target] option 6 is no longer supported. Use 7 or later."

### Context
I have verified this as a regression between jdk/jre 11 to 12. I can compile the same checkout of version gradle 5.4.0 on jdk/jre 11.

### Steps to Reproduce 
1. ensure jdk/jre 12 is installed, see also [oracle](https://www.oracle.com/technetwork/java/javase/downloads/index.html)
2. clone https://github.com/gradle/gradle/releases/tag/v5.4.0
3. ./gradlew clean install -Pgradle_installPath=/tmp/gradle-5.4.0

### Your Environment
```
sw_vers -productVersion
10.14.4

java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**Comment by big-guy** [comment]
We need to support Java 6 until we deprecate/remove that as a supported option.  We use Java 11 to build Gradle since that's the last version that supports building for Java 6.  We do support _running_ Gradle with Java 12.
