### ISSUE TITLE
OOM error with incremental option enabled for missing class import

### ISSUE THREAD

**Issue by kavinkumarks** [gradle/gradle#7884]
### Expected Behavior
When I use incremental option enabled with gradle 3.5 for compilation error (in this case for missing class import), it should fail with proper message.

### Current Behavior
When I use incremental option enabled with gradle 3.5 for compilation error (in this case for missing class import), it fails with OOM error.

### Context
We have continuous integration setup for our modules and due to this error either the job for one of the modules related to this error runs forever or shoots up the CPU to 100% where the CI is configured.

### Steps to Reproduce (for bugs)
1. Change one of the classes to have an incorrect missing class import
2. Run "clean build" task with incremental option enabled.
NOTE I tried this with another module and it doesn't show up this error.

### Your Environment
https://scans.gradle.com/s/xqa5m3ndwdb4y/

**Comment by big-guy** [comment]
@kavinkumarks could you try your build with Gradle 4.10 or 5.0? 

@oehme does this ring any bells for you?

**Comment by oehme** [comment]
Nope, never seen something like that. If Gradle 4.10 doesn't fix it, please provide a reproducible sample project.

**Comment by kavinkumarks** [comment]
@big-guy I tried with 4.10 and the build keeps on running for more than 3 hrs.

**Comment by kavinkumarks** [comment]
I am trying to analyze this with the heap dump.Will the heap dump help as I shouldn't share the project?

**Comment by oehme** [comment]
A heap dump would help. A thread dump would be useful too.

**Comment by kavinkumarks** [comment]
Here are some screenshots for the gradle process and heap dump.I will attach the dumps soon.
![screenshot from 2018-12-03 16-10-06](https://user-images.githubusercontent.com/20789766/49372984-76454500-f722-11e8-9307-b30f2c899388.png)
![screenshot from 2018-12-03 16-10-32](https://user-images.githubusercontent.com/20789766/49372985-76454500-f722-11e8-8516-692b94e0aac0.png)

**Comment by oehme** [comment]
This process is stuck in javac. There is no special code for incremental compilation in there, that all happens before/after javac is done. So I doubt this is related to incremental compile, especially because this is a clean CI build. 

It may be that javac needs a bit more memory, depending on the size and complexity of your project. You can change it like this: `compileJava.options.forkOptions.memoryMaximumSize = '4g'`.

**Comment by kavinkumarks** [comment]
Seems this helped.Thanks!

I will monitor our CI jobs and update if this still an issue.

**Comment by oehme** [comment]
Thank you, I'll close this as not Gradle-related for now.
