### ISSUE TITLE
Gradle 7.0 w/ Java 11 non-module projects generates broken class-/modulepath for Eclipse

### ISSUE THREAD

**Issue by mduft** [gradle/gradle#16922]
### Expected Behavior

We upgraded our Gradle 6.8 project to 7.0 and expected everything to work as it has done previously after fixing all the issues according to the upgrade guide.

### Current Behavior

After upgrading to 7.0, running our tests, and also the programs itself works from the CLI, but no longer from Eclipse. I diffed some, and found out that it is caused by these entries in the generated .classpath files: `<attribute name="module" value="true"/>`

The problem we are getting when launching something from within the IDE, but not from the CLI is:

```
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/AbstractLoggerAdapter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1096)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:759)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:680)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:605)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.apache.logging.log4j.slf4j@2.14.1/org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:36)
	at org.slf4j@1.7.30/org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j@1.7.30/org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j@1.7.30/org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j@1.7.30/org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j@1.7.30/org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at io.bdeploy.common.ActivityReporter$Stream.<clinit>(ActivityReporter.java:121)
	at io.bdeploy.common.cli.ToolBase.toolMain(ToolBase.java:100)
	at io.bdeploy.minion.cli.MinionServerCli.main(MinionServerCli.java:44)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.spi.AbstractLoggerAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
```

### Context
We have a multi project build. Some of the projects are Java 8 for compatibility, and some are Java 11 where possible, but do *not* use JPMS, we do not have module-info.java's anywhere.

### Steps to Reproduce 
The issue is exposed on this commit: https://github.com/bdeployteam/bdeploy/commit/b5dac38c226067f4c158b1a7b702ee0db9783cdb
We reverted to 6.8 on the next commit: https://github.com/bdeployteam/bdeploy/commit/8e95a3a872152e117431b47bf1acb52ae5b5b31b

### Your Environment

Happens on Windows and Linux, only in Eclipse, not on CLI, on Java 11 projects which are not modules, depending on logging libraries which *are* modules (SLF4J, Log4j2).

Build scan URL:
https://scans.gradle.com/s/i6cojjndbh6gu

**Comment by mduft** [comment]
When I add this to all projects, things return to working, but I'm not sure whether this is correct, and should be required by projects?

```
    java {
        // enabled by default in gradle 7.0 - breaks executing anything from eclipse, but not from the CLI
        modularity.inferModulePath = false
    }
```

**Comment by donat** [comment]
@mduft I'm looking into this issue now. How can I launch the application on the command line?

**Comment by donat** [comment]
I'm assuming you don't use Buildship in Eclipse, right?

**Comment by donat** [comment]
Using `modularity.inferModulePath = false` is the correct way to solve your issue. Gradle 7.0 enabled module support by default: https://docs.gradle.org/current/userguide/java_library_plugin.html#disabling_java_module_support You'd get the same error if you use Gradle 6.8 and configure  `modularity.inferModulePath = true`.

The difference between the command line and eclipse could be because the dependency configuration cannot be precisely mapped from Gradle to Eclipse. The `eclipse` plugin tries to merge all configurations and create a flat list of dependencies for each project. 

Still, it would be interesting to check what's the difference between the CLI and Eclipse. Could you paste the following information here?
- the classpath from the CLI when you run the app (i.e. the corresponding lines from the output of `./gradlew run --debug`).
- the relevant `.classpath` files generated by the Eclipse plugin with Gradel 7.0.
- the classpath of the running application from Eclipse (You can get the classpath from the Debug view IIRC).

**Comment by mduft** [comment]
Thanks for following up :) Here is the information requested. I discovered that it is not as easy to reproduce as I thought it to be. I need to actually setup a system using our software, because that is the only way to get until a point where logging is actually involved - all the "basic" and "easy to launch" commands I could tell you how to run just write on the command line and that - unfortunately - works :| So I have done some setup, and ran the same command both from eclipse as well as from gradle.

The console output when running the command using gradle, including the expected log output (`Logging into ...`)
[bdeploy-modules-gradle.txt](https://github.com/gradle/gradle/files/6385044/bdeploy-modules-gradle.txt)

The command line according to eclipse when running the same thing from Eclipse, plus the output before the command dies.
[bdeploy-modules-eclipse.txt](https://github.com/gradle/gradle/files/6385045/bdeploy-modules-eclipse.txt)

The .classpath file as generated by Gradle 7.0 default:
[bdeploy-minion-classpath-with-modules.txt](https://github.com/gradle/gradle/files/6385053/bdeploy-minion-classpath-with-modules.txt)

The .classpath file as generated by Gradle 6.8 or Gradle 7.0 with `modularity.inferModulePath = false`
[bdeploy-minion-classpath-without-modules.txt](https://github.com/gradle/gradle/files/6385082/bdeploy-minion-classpath-without-modules.txt)

If you would like to reproduce this on your own, I would create a dummy command in our infrastructure which is easy to launch and does some logging...

**Comment by donat** [comment]
Thanks for submitting those files.

> If you would like to reproduce this on your own, I would create a dummy command in our infrastructure which is easy to launch and does some logging...

I think that would be super-helpful. Please do it if possible. I'll keep investigating in the meanwhile.

**Comment by mduft** [comment]
OK. I created a tiny test tool in: https://github.com/bdeployteam/bdeploy/commit/e4433784653d1d235fd04d353810b9217611b6bd

This basically only tries to log a single line containing `GRADLE Modular Classpath Test Tool`.

To run it:

- You need a recent node/npm installed, I currently use 14.15.1 - compiling also builds an angular app...
- You need Java 11 in both the command line and Eclipse. I hope there are no other requirements.
- `./gradlew cleanEclipse eclipse` and import all projects into an empty Eclipse workspace.
- Find the class `io.bdeploy.minion.cli.GradleTestTool` and run its `main` method (right click -> Run As -> Java Application). This will *not* work :)
- On the command line, change to the `minion` directory, and `../gradlew run --args="testGradle"`. This works no matter the setting of `modularity.inferModulePath`.
- The top-level `build.gradle` contains the commented out `modularity.inferModulePath = false`. When commenting in and repeating the procedure, everything works :)

**Comment by donat** [comment]
I think we've found the source of difference between the CLI and the IDE use-case. The `eclipse` plugin adds the module annotation to all the dependencies regardless of whether or not the container project is modular. This should not be the case. We've fixed this issue. The changes will be part of Gradle 7.0.1.

**Comment by donat** [comment]
Btw, the sample you created was really helpful. I was able to verify that my changes fixed your issue in no time.

**Comment by donat** [comment]
Fixed in https://github.com/gradle/gradle/pull/16993.

**Comment by mduft** [comment]
Thanks a ton for the *very* quick investigation and fix :)
