### ISSUE TITLE
Sync failed after upgrading to gradle 6.0.1

### ISSUE THREAD

**Issue by houcheng** [gradle/gradle#11602]
My project is a kotlin/spring based Gradle project with IntelliJ 2018.3 for developing and
and Gradle 5.6.1 for building. Recently I upgraded the project's Gradle version to 6.0.1 
and build is fine but get this build error during syncing the Gradle:

    build gradleextensions NoClassDefFoundError: 
        org/gradle/api/internal/plugins/DefaultConvention

I've tried killed all JVM and restarted the IntelliJ but still get the same error message.
Reverting to previous Gradle version and all works well.
So, is that indicating this may be a bug in Gradle 6.0.1 ? 

Thank you.

**Comment by ljacomet** [comment]
Did you take a look at [the upgrade guide](https://docs.gradle.org/6.0.1/userguide/upgrading_version_5.html)?

With the information provided, there is zero chance to give you any meaningful advice. Any chance you could share a reproducer? A build scan?

**Comment by houcheng** [comment]
Hi @ljacomet 

Here is my build scan in which I used a lot of deprecated commands but the build is fine.

https://scans.gradle.com/s/y67hhyxckdg52

And this is the snapshot of sync failure in IntelliJ:

![image](https://user-images.githubusercontent.com/3364461/70367974-a187e480-18e0-11ea-9fec-8f036b1e942d.png)

**Comment by houcheng** [comment]
Hi @ljacomet,

Thank you for the comments. 
This issue is resolved by updating the intellJ to the latest version.

**Comment by motal** [comment]
still not working on latest intlliJ with gradle 6.0.1
