### PR TITLE
Upgrade wrapper to latest nightly

### PR DESCRIPTION
**Pull request by asodja**
Should fix issues with Groovy compiler throwing `NoClassDefFoundError` as described in #22531.

### CODE REVIEW

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
@bot-gradle test and merge

**Comment by asodja** [comment]
@bot-gradle cancel

**Comment by asodja** [comment]
@bot-gradle test this

**Comment by asodja** [comment]
Wrapper changes: https://github.com/gradle/gradle/commit/1fe8b083d15a9fb2a8a5f1b94420c8e50d0a50c9

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy [hunk 1]
```diff
@@ -71,7 +71,7 @@ class WrapperGenerationIntegrationTest extends AbstractIntegrationSpec {
         executer.inDirectory(file("second")).withTasks("wrapper").run()
 
         then: "the checksum should be constant (unless there are code changes)"
-        Hashing.sha256().hashFile(file("first/gradle/wrapper/gradle-wrapper.jar")) == HashCode.fromString("c5a643cf80162e665cc228f7b16f343fef868e47d3a4836f62e18b7e17ac018a")
+        Hashing.sha256().hashFile(file("first/gradle/wrapper/gradle-wrapper.jar")) == HashCode.fromString("577b2de036000db2e0f04f2ec842a4f1e648c8b6f9c87f29a8d896acb1732538")
```
Comment (wolfs) [inline subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:74]: Alright, seems like the change is caused by https://github.com/gradle/gradle/pull/19570. I suppose we can go forward with upgrading the wrapper.

**Review by wolfs — APPROVED** [review]

File: subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy (hunk 1 above)
Comment (big-guy) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:74]: Why does the version of Gradle we use to build Gradle affect this?

Comment (wolfs) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:74]: Because the new version of Gradle is used to build the jar we put in the distribution.

Comment (big-guy) [reply subprojects/wrapper/src/integTest/groovy/org/gradle/integtests/WrapperGenerationIntegrationTest.groovy:74]: Ah, I understand.  The wrapper jar is built like any other jar. I was thinking it was built by the Gradle-under-test in this case.

**Comment by asodja** [comment]
@bot-gradle test and merge
