### ISSUE TITLE
Eclipse Test Dependency Configuration Overrides Regular Dependency

### ISSUE THREAD

**Issue by romeara** [gradle/gradle#22838]
As of Gradle 7.5, when importing/operating on a project via the Buildship plug-in and the Gradle "eclipse" plug-in, dependencies on other projects used as both production and test code are not correctly configured. Eclipse only allow a project to be added once, and it has one value for "test sources only" - it appears that if the project is being used as a test-style dependency and an api dependency, the test dependency's setting of "test sources only" overrides the api dependency's value, resulting in Eclipse marking complication errors. This behavior works correctly in 7.4.2.

This pull request may be relevant: https://github.com/gradle/gradle/pull/19310

### Expected Behavior

```
dependencies {
	api project(':project1')
	api project(':project3')

	testFixturesApi project(':project2')
	testFixturesApi project(':project1')

	testImplementation testFixtures(project(":project3"))
	testImplementation testFixtures(project(":project1"))
}
```

All projects should be marked as "test-only = false"

### Current Behavior

Example:

```
dependencies {
	api project(':project1')
	api project(':project3')

	testFixturesApi project(':project2')
	testFixturesApi project(':project1')

	testImplementation testFixtures(project(":project3"))
	testImplementation testFixtures(project(":project1"))
}
```

`project1` and `project3` are marked as "test-only = true" in this setup, while `project2` is marked as "test-only = false"

### Context

This has prevented updating past Gradle 7.4.2, as it breaks the Eclipse development environment

### Steps to Reproduce 

Reproduction project: https://github.com/romeara/gradle-eclipse-classpath-bug

Relevant branches:
`expected-behavior`
`current-behavior`

To reproduce, import into Eclipse using Buildship. Running "Gradle -> Refresh projects" after switching branches is sufficient to trigger the change in dependency type. Note that given the lack of actual source files, there will not be compilation errors, the dependency type will just change.

This behavior also appears in 7.5.1, the latest version at time of reporting

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

----

To go back to the previous behavior you can use the Gradle `eclipse` plugin to edit the test entry attributes in the Eclipse `.classpath` file using

```groovy
eclipse.classpath.file.whenMerged {}
```

**Comment by oleosterhagen** [comment]
There is a small inaccuracy in the description: In this example, the dependency from `project4` to `project2` should have the `test` attribute, because it is only used as a test dependency.

The dependencies to `project1` and `project3` should not have this attribute, because they also exist as non-test dependencies.
