### ISSUE TITLE
Updating gradle to V3.3 makes Eclipse unable to resolve dependencies.

### ISSUE THREAD

**Issue by Sonorks** [gradle/gradle#9799]
Eclipse v4.11.0 doesn't import the gradle dependencies so the java classes show the error 'the import *** cannot be resolved'.

### Expected Behavior
Gradle should import all the libraries and be shown in the 'Gradle Dependencies' classpath container

### Current Behavior
Gradle task like 'refresh dependencies','refresh all' or 'build' are finishing ok but dependencies are not shown in eclipse and java classes are in error because unresolved imports. 

### Context

It was working with gradle v2.4. Upgrading to gradle v3.3 made it fail. I've read that in recent versions of eclipse the method 'compile' is deprecated, but I tried 'api' and 'implementation' but it doesn't work.

### Steps to Reproduce 

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'eclipse-wtp'
apply plugin: 'jacoco'

	dependencies{
		// Proyectos
		// Librerias
		compile project.ext["commons"]
		compile project.ext["cxf.foundation"]
		compile project.ext["ehcache"]
		compile project.ext["log4j"]
		compile project.ext["xml"]
		compile project.ext["javaee"]
}

These project.ext["..."] are filetrees defined in the root project.

### Your Environment

Eclipse IDE for Enterprise Java Developers.
Version: 2019-03 (4.11.0)
Build id: 20190314-1200

Gradle version: 3.3

The project works with Gradle STS.

Gradle buildship plugin for eclipse version 3.0

**Comment by big-guy** [comment]
Are you importing the project with Buildship directly or are you generating the Eclipse metadata files with `gradle eclipse` and then importing that?

Is it possible for you to try a newer version of Gradle? 5.4.1 is the latest.

You can try getting more help on our forums: https://discuss.gradle.org/

**Comment by Sonorks** [comment]
Hi, thanks for answering my questions. I'm importing the project directly
with buildship, I've tried with newest versions (including 5.4.1) but it
doesn't work. I think the problem might be that the metadata generated by
eclipse was generated before with gradle STS, and it's supported by
springsource (not buildship) but also I tried the task clean eclipse and
deleting this files and none worked. Plus, I tried changing the nature of
the project and even uninstalling the STS plugin but it doesn't work.

PD: Android Studio and IntelliJ resolve the dependencies without any
problem or additional stuffs.

Thank you!
