### PR TITLE
Remove Play 2.2

### PR DESCRIPTION
**Pull request by benmccann**
### Contributor Checklist
- [X] [Review Contribution Guidelines](https://github.com/gradle/gradle/blob/master/.github/CONTRIBUTING.md)
- [X] [Sign Gradle CLA](http://gradle.org/contributor-license-agreement/)
- [X] Check ["Allow edit from maintainers" option](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) in pull request so that additional changes can be pushed by Gradle team
- [X] Provide integration tests (under `<subproject>/src/integTest`) to verify changes from a user perspective
- [X] Provide unit tests (under `<subproject>/src/test`) to verify logic
- [X] Update User Guide, DSL Reference, and Javadoc for public-facing changes
- [ ] Ensure that tests pass locally: `./gradlew <changed-subproject>:check`

### Gradle Core Team Checklist
- [ ] Verify design and implementation 
- [ ] Verify test coverage and CI build status
- [ ] Verify documentation
- [ ] Recognize contributor in release notes

### CODE REVIEW

**Comment by blindpirate** [comment]
Thank you very much for this. Let's finish #3029 and #3315 first and I'll be back to review this.

**Comment by marcospereira** [comment]
@blindpirate, I would say that it could be good to merge #3314 before this too.

@benmccann maybe we should remove Play 2.3 too? Or at least make Play 2.6 the new default. Of course, we can have new PRs to handle these.

**Comment by benmccann** [comment]
Yes, I think it would be good have the default be whatever the latest version is

**Comment by marcospereira** [comment]
@benmccann there are conflicts here now. Moreover, you may want to review the code that changed in #3314.

**Comment by benmccann** [comment]
Thanks @marcospereira. I've rebased this PR. I appreciate the cleanup in your PR that made this easier by making the version string hardcoded in fewer places

**Comment by benmccann** [comment]
@blindpirate I think this one is ready to merge now

**Comment by blindpirate** [comment]
@benmccann Thanks a lot for your contribution. Generally we don't remove support in the middle of a major version. We usually put deprecation warnings in advance and do the real removal in next major release. So I'll provide some deprecation warnings and merge this for 5.0.

**Comment by benmccann** [comment]
Sounds good. Thanks!

**Comment by marcphilipp** [comment]
Now that we've started to work on 5.0, it's time to revisit this PR.

@benmccann Do you have time to rebase it onto the current master?

**Comment by benmccann** [comment]
@marcphilipp done. Thanks!

**Comment by marcphilipp** [comment]
There seems to be a compilation error now:

```
:javascript:compileTestFixturesGroovy
/home/tcagent1/agent/work/668602365d1521fc/subprojects/platform-play/src/main/java/org/gradle/play/internal/run/PlayApplicationRunner.java:65: error: cannot find symbol
            this.isPlay22 = adapter instanceof PlayRunAdapterV22X;
                                               ^
  symbol:   class PlayRunAdapterV22X
  location: class PlayApplicationRunner.PlayClassloaderMonitorDeploymentDecorator
```

Source: https://builds.gradle.org/viewLog.html?buildId=14910120&tab=buildResultsDiv&buildTypeId=Gradle_Check_SanityCheck

@benmccann Could you please take a look?

**Comment by benmccann** [comment]
Oops, sorry. It's been updated now @marcphilipp 

Unfortunately I didn't retest since fixing this error because it seems `./gradlew platform-play:check` now requires Java 9 since I rebased and I haven't installed Java 9 yet. This was such a simple fix that I'm hopeful it won't cause any other issues, but please let me know if there's another build error. Is there anyway for me to see the continuous build? Or it's internal to Gradle only?

**Comment by marcphilipp** [comment]
It's public, you need to click "Log in as a guest" on the bottom right.

Now there is a Checksyle violation:
https://builds.gradle.org/repository/download/Gradle_Check_SanityCheck/14938369:id/report-platformPlay-checkstyle-main.html#f-/home/tcagent1/agent/work/668602365d1521fc/subprojects/platform-play/src/main/java/org/gradle/play/internal/platform/PlayMajorVersion.java

**Comment by benmccann** [comment]
Thanks. Fixed the checkstyle violation

How does a new build get kicked off? It's still showing me the checkstyle violation, so I can't tell if everything is fixed yet

**Comment by marcphilipp** [comment]
Thanks! PR builds need to be started manually. Here's another one: https://builds.gradle.org/viewQueued.html?itemId=14939413&tab=queuedBuildOverviewTab

**Comment by benmccann** [comment]
Thanks @marcphilipp . I think everything's passing now. Let me know if that's not the case

**Comment by benmccann** [comment]
Thank you!!
