### ISSUE TITLE
Failed scala compilation on large projects caused by missing classes (closed classloader?)

### ISSUE THREAD

**Issue by mvitaly** [gradle/gradle#16408]
Running a gradle project with about 50 included builds of scala projects.
The build fails randomly with the following error:
```
...
> Task :[ONE_OF_THE_INCLUDED_BUILDS]:compileScala
Exception when compiling 7 sources to [...ONE_OF_THE_INCLUDED_BUILDS]/build/classes/scala/main
java.lang.NoClassDefFoundError: scala/tools/nsc/typechecker/Namers$Namer$$anonfun$typeErrorHandler$1
scala.tools.nsc.typechecker.Namers$Namer.typeErrorHandler(Namers.scala:112)
scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1864)
scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:937)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2059)
scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2057)
scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2052)
scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1542)
scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1698)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5347)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5788)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3335)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3335)
scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2017)
scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1883)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5645)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5788)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3335)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3335)
scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5354)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5647)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5788)
scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3335)
scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3335)
scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5354)
scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5647)
scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1511)
scala.tools.nsc.Global$Run.compileUnits(Global.scala:1495)
scala.tools.nsc.Global$Run.compileSources(Global.scala:1488)
scala.tools.nsc.Global$Run.compile(Global.scala:1614)
xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
xsbt.CompilerInterface.run(CompilerInterface.scala:39)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:167)
org.gradle.api.internal.tasks.scala.ZincScalaCompilerFacade.execute(ZincScalaCompilerFacade.java:52)
org.gradle.api.internal.tasks.scala.ZincScalaCompilerFacade.execute(ZincScalaCompilerFacade.java:31)
org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:135)
org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:85)
org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:55)
org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
java.lang.Thread.run(Thread.java:748)
```

It seems to fail with different included builds, different classes with the NoClassDefFoundError and if I rerun the build multiple times it would succeed eventually.
For example another included build is failing with:
`java.lang.NoClassDefFoundError: scala/tools/nsc/classpath/FileUtils$FileOps$`

The bug is similar to https://github.com/sbt/zinc/issues/914 , seems to be resolved in zinc 1.4.0 . I've tried to backport the fix to zinc 1.3.5 with almost no difference in the output.

### Expected Behavior
Successful build on the first try.

### Current Behavior
Throwing an error. Succeeds after a retry or two.

### Context
This is causing unstable builds, false tests failure alerts.

### Steps to Reproduce
The project is too big to share. Can provide any additional debug info.

### Your Environment
Running within docker.
Tried to run with max-workers=1, max-workers=4, giving scala task 4gb of heap and 2gb of max metaspace memory.

**Comment by mvitaly** [comment]
Is it possible that it's caused by the cache limit constants in ZincScalaCompilerFactory introduced in #12866 :
`CLASSLOADER_CACHE_SIZE = 4` or `COMPILER_CLASSLOADER_CACHE_SIZE = 4` ?

If I understand correctly the value 4 means that if 4 classloaders are cached, the next one will evict *and close* one of the existing cached classloaders, which would cause it to stop loading any new classes and if it's still being in use would throw NoClassDefFoundError.

**Comment by mvitaly** [comment]
tested with the PR fix above and didn't see any failures

**Comment by mvitaly** [comment]
The PR above makes the failure occurrences less frequent, but I still saw class loading errors. The next thing I tried is to figure out the magic number of 4 that is used in two places to construct caches in ZincScalaCompilerFactory .
Instead of using a limit for the cache, I switched to Guava cache soft references and the builds are not failing now. The change was too trivial with no changes to removalListener logic. So I assume it leaks file descriptors, but at least not to a point where everything crashes within a single (huge) build.
Thinking about creating a test case to reproduce it and maybe adding another part to the cache about having underlying urlclassloaders closed when the softreference of the outer classloader is garbage collected.

**Comment by big-guy** [comment]
@mvitaly I replied on Slack too.

When you say you're still seeing issues with missing classes, are you seeing classes missing from other project's that you depend on?
e.g., if project A depends on B, do you see failures in A about classes missing from B?
