### ISSUE TITLE
Upgrading Gradle from 9.6.1 to 9.7.0 causes missing gradle-public-api-legacy module

### ISSUE THREAD

**Issue by Zesko** [gradle/gradle#38852]
### Current Behavior

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'limine-entry-tool'.
> Cannot find module 'gradle-public-api-legacy' in distribution directory '/usr/share/java/gradle'.
```

### Expected Behavior

The build works fine with Gradle 9.6.1, but there is no `gradle-public-api-legacy` in `/usr/share/java/gradle/`

### Self-contained Reproducer Project

After upgrading Gradle from version 9.6.1 to 9.7.0 on Arch Linux system, I tried to build limine-entry-tool with GraalVM 25.2.4, but the build fails because gradle-public-api-legacy cannot be found in the distribution directory?

### Gradle version

9.7.0

### Gradle version that used to work

9.6.1

**Comment by JingMatrix** [comment]
This isn't a Gradle regression — it's an Arch Linux packaging bug. I hit the same thing and tracked it down.

Gradle 9.7.0 added a new `lib/api/` subdirectory to the distribution:

```
gradle-9.7.0/lib/api/gradle-public-api-legacy-9.7.0.jar
gradle-9.7.0/lib/api/gradle-public-api-legacy.properties
```

Arch's [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/gradle/-/blob/main/PKGBUILD) only installs `lib/`, `lib/plugins/` and `lib/agents/`:

```sh
install -Dm 644 lib/*.jar lib/*.properties "${pkgdir}"/usr/share/java/${pkgname}/lib
install -Dm 644 lib/plugins/*.jar lib/plugins/*.properties "${pkgdir}"/usr/share/java/${pkgname}/lib/plugins
install -Dm 644 lib/agents/*.jar lib/agents/*.properties "${pkgdir}"/usr/share/java/${pkgname}/lib/agents
```

so `lib/api/` is silently dropped and `/usr/share/java/gradle/lib/api/` doesn't exist. Nothing in 9.6.1 needed it, which is why it only shows up after the upgrade.

`KotlinScriptClassPathProvider` resolves the `gradle-public-api-legacy` module to build the compile classpath for `.gradle.kts` scripts, so any Kotlin DSL build fails at configuration time. A Groovy DSL project still builds fine on the same installation — that's an easy way to confirm the diagnosis.

Workaround until the package is fixed — restore the directory from the official distribution:

```sh
curl -O https://services.gradle.org/distributions/gradle-9.7.0-bin.zip
unzip -j gradle-9.7.0-bin.zip 'gradle-9.7.0/lib/api/*' -d /tmp/gradle-lib-api
sudo install -d -m755 /usr/share/java/gradle/lib/api
sudo install -m644 /tmp/gradle-lib-api/* /usr/share/java/gradle/lib/api/
gradle --stop
```

`gradle --stop` matters: `GradleInstallation.findLibDirs` walks `lib/` and its subdirectories once at daemon startup, so a running daemon keeps serving the old module list and you'll see the identical error until it's restarted.

These files aren't tracked by pacman and the jar name is version-stamped, so remove `/usr/share/java/gradle/lib/api/` when upgrading past 9.7.0.

The real fix is one more `install` line in the PKGBUILD. There's no Arch issue for it yet as far as I can see — worth filing on the [package tracker](https://gitlab.archlinux.org/archlinux/packaging/packages/gradle/-/issues) (same class of bug as their earlier "Ant missing from installed modules"). This one can probably be closed here.

One thing that might still be worth doing upstream: the error message names the distribution directory but not the module's expected location, and `lib/api/` is a new directory that repackagers have no signal about. A note in the 9.7.0 release notes, or an error hint pointing at the missing directory, would have saved the hunt.

**Comment by ov7a** [comment]
Similar to 
* https://github.com/gradle/gradle/issues/36966

This is not a Gradle issue, but rather an Arch Linux packaging bug. Thanks @JingMatrix for the detailed explanation.

Please report this to the package maintainers.

**Comment by letorbi** [comment]
I wrote an email to the maintainer of the package, since I don't have an account to create a bug in the package tracker yet. Hope it gets through...

**Comment by kociap** [comment]
Already fixed in [96285255](https://gitlab.archlinux.org/archlinux/packaging/packages/gradle/-/commit/96285255a6d906ccdc99b03ce0a4da23735a1591). Package is in testing now.
