### ISSUE TITLE
In 4.8, project.gradle.taskGraph fails with NoSuchMethodError

### ISSUE THREAD

**Issue by staffanf** [gradle/gradle#5689]
After upgrading the gradle wrapper to 4.8, one of my tasks fails while accessing `project.gradle.taskGraph` from a groovy implemented task using CompileStatic.

### Expected Behavior
4.8 should work as before (I guess)

### Current Behavior
I produced this example
https://github.com/staffanf/gradle-4.8-taskgraph-error
that shows the error using TestKit.

This fails with the error message.
```Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.GradleInternal.getTaskGraph()Lorg/gradle/execution/TaskGraphExecuter;```
 
### Context
The real (not simplified as in the example) task verifies the version syntax of any projects with a "release" task when the taskGraph is ready. This could possibly be done is a different way.

### Steps to Reproduce (for bugs)
Pull  https://github.com/staffanf/gradle-4.8-taskgraph-error
Execute ```./gradlew build```

### Workaround
Seems to work when CompileStatic is removed from the task. Not sure why.

### Your Environment
Gradle 4.8

**Comment by wolfs** [comment]
@staffanf The problem is that your task is being compiled to use `GradleInternal.getTaskGraph`. The return type of this method changed in Gradle 4.8. The return type of `Gradle.getTaskGraph` did not change though.

I guess the `project` your are referencing is of type `ProjectInternal`. How did you get a hold of that? The return type of `DefaultTask.getProject()` should be `Project` and not `ProjectInternal`.

Please try to use the public API whenever possible.

**Comment by staffanf** [comment]
@wolfs I thought I was using the public API. The code is referencing the "Task.project" property using groovy.

The offending line is here [VerifyVersionTask.groovy#L20](https://github.com/staffanf/gradle-4.8-taskgraph-error/blob/d50adb3f552a57021439bd69728e1565eef534b3/src/main/groovy/not/so/important/tasks/VerifyVersionTask.groovy#L20)

I extend DefaultTask which in turn extends the internal AbstractTask.
I call the public getProject() which returns is a ProjectInternal but I use it as a Project by calling the public getGradle().
ProjectInternal however has overridden getGradle() to return a GradleInternal, so the actual implementation of getTaskGraph() is a TaskExecuter in 4.7 and a TaskExecutionGraphInternal in 4.8.

I'm still unsure why this fails. Changing the wrapper to 4.8 instead will switch which test case in the example that fails.

**Comment by wolfs** [comment]
@staffanf You are right, you are only using the public API. I am not completely sure how the static Groovy compiler is deciding that `project` is of type `ProjectInternal`, since `AbstractTask.getProject()` returns `Project` and not `ProjectInternal`. I guess the `project` field in `AbstractTask` is to blame...

One (ugly) workaround for you would be to do something like this:
```groovy
Project project = this.project
project.gradle.taskGraph
```
That should work both for Gradle 4.8 and previous versions, right?

How big is the impact of this change for you? Can you work around it or does it block you from upgrading to 4.8?

**Comment by staffanf** [comment]
Not a blocker at all. I actually removed the @CompileStatic for the task since there wasn't much code being executed. I will try your suggestion tomorrow.

**Comment by oehme** [comment]
Closing since this was an internal API usage.
