### ISSUE TITLE
Symbolic links are completely broken with Gradle 9.2.0+

### ISSUE THREAD

**Issue by xxDark** [gradle/gradle#36483]
### Current Behavior

Init script:
```
FAILURE: Build failed with an exception.

* Where:
Initialization script 'F:\gradle\init.d\env.init.gradle.kts' line: 2

* What went wrong:
Script compilation errors:

  Line 02: import org.gradle.kotlin.dsl.support.serviceOf
                                                ^ Unresolved reference 'serviceOf'.

  Line 06:     val processEnvironment = serviceOf<ProcessEnvironment>()
                                        ^ Unresolved reference 'serviceOf'.

  Line 07:     val envFile = rootDir.resolve(".env")
                                     ^ Unresolved reference 'resolve'.

  Line 12:     }.useLines {
                 ^ Unresolved reference 'useLines'.

  Line 13:         it.forEach {
                   ^ Unresolved reference 'it'.

  Line 14:             if (it.isEmpty() || it[0] == '#') return@forEach
                           ^ Unresolved reference 'it'.

  Line 14:             if (it.isEmpty() || it[0] == '#') return@forEach
                                           ^ Unresolved reference 'it'.

  Line 14:             if (it.isEmpty() || it[0] == '#') return@forEach
                                             ^ No 'get' operator method providing array access.

  Line 15:             var idx = it.indexOf('=')
                                 ^ Unresolved reference 'it'.

  Line 16:             require(idx != -1) { "Missing '=' separator" }
                       ^ Unresolved reference 'require'.

  Line 17:             var key = it.substring(0, idx)
                                 ^ Unresolved reference 'it'.

  Line 18:             val value = it.substring(idx + 1)
                                   ^ Unresolved reference 'it'.

12 errors
```

Even with completely harmless init script (no use of internal API):
Single line:
```
java.lang.System.out.hashCode()
```

```
java.lang.NoSuchMethodError: 'void Env_init_gradle.<init>(org.gradle.kotlin.dsl.support.KotlinScriptHost, org.gradle.api.invocation.Gradle)'
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:516)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:214)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:133)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory.create$lambda$0(KotlinScriptPluginFactory.kt:61)
```

Upon project import if init script is removed:
```

java.lang.NoSuchMethodError: 'void Settings_gradle.<init>(org.gradle.kotlin.dsl.support.KotlinScriptHost, org.gradle.plugin.use.PluginDependenciesSpec, org.gradle.api.initialization.Settings)'
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:516)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:194)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:133)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory.create$lambda$0(KotlinScriptPluginFactory.kt:61)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:35)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:68)
```

### Expected Behavior

Everything works.

### Context (optional)

The script is used to load environment variables and some system properties.
After upgrading to 9.2.0, the script is completely broken due to somehow missing imports.
Importing kotlin.io does not help.
Nuking gradle cache does not help.
`org.gradle.kotlin.dsl.support.serviceOf` exists (?) but does not get picked up either.
https://github.com/gradle/gradle/blob/a42f1f576913f31a1104cfc6131e165cb19e26a1/platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/SettingsExtensions.kt#L21

The problem also persists with 9.3.0

### Self-contained Reproducer Project

```kotlin
import org.gradle.internal.nativeintegration.ProcessEnvironment
import org.gradle.kotlin.dsl.support.serviceOf
import java.io.FileNotFoundException

beforeSettings {
    val processEnvironment = serviceOf<ProcessEnvironment>()
    val envFile = rootDir.resolve(".env")
    try {
        envFile.bufferedReader()
    } catch (_: FileNotFoundException) {
        return@beforeSettings
    }.useLines {
        it.forEach {
            if (it.isEmpty() || it[0] == '#') return@forEach
            var idx = it.indexOf('=')
            require(idx != -1) { "Missing '=' separator" }
            var key = it.substring(0, idx)
            val value = it.substring(idx + 1)
			if (key.startsWith("-D")) {
				System.setProperty(key.substring(2), value)
				return@forEach
			}
            idx = key.indexOf('|')
            if (idx != -1) {
                val property = key.substring(idx + 1)
                key = key.substring(0, idx)
                rootProject {
                    val ext = rootProject.extensions.getByName("ext") as ExtraPropertiesExtension
                    ext[property] = value
                }
            }
            processEnvironment.setEnvironmentVariable(key, value)
        }
    }
}
```

### Gradle version

9.3.0

### Gradle version that used to work

9.1.0

### Your Environment (optional)

Windows 10.
Gradle home is located on the ram disk. The path is changed by creating a symbolic link from original gradle home to the drive.
The symbolic link is created like this:
```
New-Item -Path "${userHome}\.gradle"-ItemType SymbolicLink -Value "${driveLetter}:\gradle"
```

**Comment by xxDark** [comment]
The problem was fixed after upgrading to 9.4.0 from here.
https://services.gradle.org/distributions-snapshots/gradle-9.4.0-20260127023744+0000-bin.zip
Weird. Is there a way for me to know which commit fixed this?

**Comment by tresat** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer project, we may be also able to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). Please make sure that the issue reproduces in [GitHub Action](https://github.com/gradle/gradle-issue-reproducer/blob/kotlin-dsl/.github/workflows/run-reproducer.yml). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.

This issue will be closed after 7 days unless you provide more information.

***

Can you please confirm this is fixed in the [latest 9.4 nightly](https://services.gradle.org/distributions-snapshots/gradle-9.4.0-20260129021521+0000-bin.zip)?

**Comment by kurahaupo** [comment]
@xxDark 

> Is there a way for me to know which commit fixed this?

If you're really keen you can use `git bisect` to find the commit that fixed it. 

This sounds like `classpath` is wrong or missing from the JVM invocation. To determine that, it would help to know whether you are using `gradlew.bat` (the Windows Gradle runner) or `gradlew` (the Linux/Unix/WSL Gradle runner) (or something else).

**Comment by xxDark** [comment]
Hello! Sorry for late reply.
Yes, I'm using gradlew.bat file.
I will try make a simple reproducer as soon as possible

**Comment by xxDark** [comment]
Interesting. It only affects one specific project. I have cloned it and did a diff to see whats wrong.
Nothing is different in the file structure.
```
diff -r -qr a b -x '.git'
<empty line>
```
Even after copying all ACLs and ownership to the new directory, it still does not fail.

Further, after simply renaming the affected directory and reverting the name, the issue fixed itself.
I suppose this can be closed, as I cannot fathom what caused this... :)
And maybe I should check my drive and perhaps buy a new one...

**Comment by xxDark** [comment]
After importing the project and working on it for a while the problem is back.
One thing I noticed: the problem is present with JDK 21. With JDK 25, there is no issue.
I've managed to create a small project that the issue could be reproduced on. I will post t he setup here in a bit.

**Comment by xxDark** [comment]
```
d:\test_gradle>ls
build.gradle.kts  gradle  gradlew  gradlew.bat  settings.gradle.kts

d:\test_gradle>mkdir gradle_home

d:\test_gradle>mklink /d D:\test_gradle\gradle_symbolic_link D:\test_gradle\gradle_home
symbolic link created for D:\test_gradle\gradle_symbolic_link <<===>> D:\test_gradle\gradle_home

d:\test_gradle>set GRADLE_HOME=D:\test_gradle\gradle_symbolic_link

d:\test_gradle>set GRADLE_USER_HOME=D:\test_gradle\gradle_symbolic_link

d:\test_gradle>set JAVA_HOME=D:\jdks\azul-21.0.5

d:\test_gradle>gradlew --no-daemon
Downloading https://services.gradle.org/distributions/gradle-9.3.0-bin.zip
.............10%.............20%.............30%.............40%.............50%.............60%.............70%.............80%.............90%.............100%

Welcome to Gradle 9.3.0!

Here are the highlights of this release:
 - Test reporting improvements
 - Error and warning improvements
 - Build authoring improvements

For more details see https://docs.gradle.org/9.3.0/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/9.3.0/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build

FAILURE: Build failed with an exception.

* What went wrong:
'void Settings_gradle.<init>(org.gradle.kotlin.dsl.support.KotlinScriptHost, org.gradle.api.initialization.Settings)'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

BUILD FAILED in 19s

d:\test_gradle>set JAVA_HOME=D:\jdks\azul-25.0.1

d:\test_gradle>gradlew --no-daemon
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by net.rubygrapefruit.platform.internal.NativeLibraryLoader in an unnamed module (file:/D:/test_gradle/gradle_symbolic_link/wrapper/dists/gradle-9.3.0-bin/79n14ral3mx1ozqr3csh2u872/gradle-9.3.0/lib/native-platform-0.22-milestone-29.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/9.3.0/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build

> Task :help

Welcome to Gradle 9.3.0.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see more detail about a task, run gradlew help --task <task>

To see a list of command-line options, run gradlew --help

For more detail on using Gradle, see https://docs.gradle.org/9.3.0/userguide/command_line_interface.html

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
Consider enabling configuration cache to speed up this build: https://docs.gradle.org/9.3.0/userguide/configuration_cache_enabling.html
```

[test_gradle.zip](https://github.com/user-attachments/files/25083823/test_gradle.zip)

I'm not sure I can use the template repository as it requires setting up GRADLE_USER_HOME/GRADLE_HOME in a specific way.

**Comment by ljacomet** [comment]
This is most likely the same root cause as the following issue:
* #35572


And so this will be fixed with 9.4.0.

@xxDark If the RC, to be released soon, does not fix the issue, please let us know.
