### ISSUE TITLE
testImplementation method is not working as expected after upgrade to 7.1

### ISSUE THREAD

**Issue by santoshkumarcts** [gradle/gradle#17587]
i have upgraded gradle version from 6.4 to 7.1,

in 6.4 gradle file i had this 

testCompile (
               springBootStarterTest,
               hsqldb
       )
and with upgrade to 7.1 i changed it to

testImplementation (
               springBootStarterTest,
               hsqldb
     )
facing below exception 
ocpm.cne.config.services.TopicInfoServiceTest > getAllConfigItemsWithTopicNameAndLabelsNULLTest FAILED
    java.lang.NoClassDefFoundError at LogbackLoggingSystem.java:352
        Caused by: java.lang.ClassNotFoundException at BuiltinClassLoader.jav
