### PR TITLE
Temporarily restore changed exception

### LINKED ISSUE #26462: NowInAndroid project is not building with current `master` branch
### Current Behavior

[NowInAndroid](https://github.com/android/nowinandroid) doesn't build with latest Gradle (`master` branch).
It does however build with Gradle `8.4-rc-1`, so we just recently broke it on `master`.

### Expected Behavior

[NowInAndroid](https://github.com/android/nowinandroid) should build with latest Gradle.

### Context (optional)

I discovered this when trying to set up performance tests based on this project for Gradle.

The failure is somewhat a blocker for this effort, but I think I can work around it, if need be.

### Steps to Reproduce

Run the `assembleDebug` task on [NowInAndroid](https://github.com/android/nowinandroid) (commit `e40fb7925deac9912985522378281ce0f6c9d31a`, latest `main` branch at the moment), it results in the failure of the `:app:demoDebugOssDependencyTask` task:

```
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/component/AmbiguousVariantSelectionException
	at com.google.android.gms.oss.licenses.plugin.DependencyTask.loadArtifactInfo(DependencyTask.groovy:64)
	at com.google.android.gms.oss.licenses.plugin.DependencyTask.action(DependencyTask.groovy:51)
```

### Gradle version

8.5-20230921121928+0000

### Gradle version that used to work

8.4-rc-1

### Build scan URL (optional)

_No response_

### Your Environment (optional)

_No response_

### PR DESCRIPTION
**Pull request by tresat**
Fixes #26462

### CODE REVIEW

**Comment by tresat** [comment]
@bot-gradle test this

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousVariantSelectionException.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package org.gradle.internal.component;
+
+/**
+ * This type is {@code deprecated} and will be removed in Gradle 9.0.
+ *
+ * This is temporarily available for migration only.  Please use {@link AmbiguousArtifactVariantsException} instead.
```
Comment (jvandort) [inline subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousVariantSelectionException.java:22]:
```suggestion
 * This is temporarily available for migration only.
 * This exception class is internal and has been replaced by {@link AmbiguousArtifactVariantsException}, which is also internal. 
 * If possible, catch a {@link RuntimeException} instead to avoid depending on Gradle internal classes.
```

Thoughts?

I worry that recommending users to reference the new internal class can lead to further issues like this in the future. 

I think users will do whatever they want, including depending on internal classes. However, if we can get them to only catch `RuntimeException` and that is acceptable for them, we should try to push for that resolution.

**Review by jvandort — APPROVED** [review]

File: subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousVariantSelectionException.java (hunk 1 above)
Comment (tresat) [reply subprojects/dependency-management/src/main/java/org/gradle/internal/component/AmbiguousVariantSelectionException.java:22]: Good advice.

**Comment by tresat** [comment]
@bot-gradle test and merge
