### ISSUE TITLE
NoSuchMethodError org.gradle.api.DefaultTask.getOnlyIf when trying to run plugin compiled with Gradle 7.6 with Gradle 7.5.1

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#23520]
### Expected Behavior

There should be a way to compile plugin with Gradle 7.6, and then use it with Gradle 7.x.

I believe Gradle 7.6 should keep the return type of the method intact and/or provide alternative ways to avoid `getOnlyIf` usage.

### Current Behavior

Gradle 7.6 changes the type of `getOnlyIf` from `Spec<? super TaskInternal>` to `DescribingAndSpec<? super TaskInternal>`.

It causes `NoSuchMethodError` because the code which is compiled with Gradle 7.6 wants to find method with `org.gradle.api.internal.tasks.execution.DescribingAndSpec org.gradle.api.DefaultTask.getOnlyIf()` signature.

### Context

It breaks upgrading `sigstore-java` to Gradle 7.6:
* https://github.com/sigstore/sigstore-java/actions/runs/3752107972/jobs/6373891436#step:6:1172

```
    Caused by: java.lang.NoSuchMethodError: 'org.gradle.api.internal.tasks.execution.DescribingAndSpec org.gradle.api.DefaultTask.getOnlyIf()'
    	at dev.sigstore.sign.DefaultDerivedArtifactFile.shouldBePublished(DefaultDerivedArtifactFile.kt:34)
    	at org.gradle.api.publish.maven.internal.artifact.DerivedMavenArtifact.shouldBePublished(DerivedMavenArtifact.java:56)
    	at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.lambda$artifactsToBePublished$3(DefaultMavenPublication.java:692)
    	at org.gradle.api.internal.collections.CollectionFilter.filter(CollectionFilter.java:46)
    	at org.gradle.api.internal.collections.FilteredCollection$FilteringIterator.findNext(FilteredCollection.java:122)
    	at org.gradle.api.internal.collections.FilteredCollection$FilteringIterator.next(FilteredCollection.java:140)
    	at org.gradle.api.internal.collections.FilteredCollection.size(FilteredCollection.java:173)
    	at org.gradle.api.internal.DefaultDomainObjectCollection.size(DefaultDomainObjectCollection.java:426)
    	at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.normalizedMavenArtifacts(DefaultMavenPublication.java:672)
    	at org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.asNormalisedPublication(DefaultMavenPublication.java:646)
    	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository.computeSpec(PublishToMavenRepository.java:100)
    	at org.gradle.internal.Try.ofFailable(Try.java:41)
    	at org.gradle.internal.serialization.Cached$Deferred.result(Cached.java:53)
    	at org.gradle.internal.serialization.Cached$Deferred.writeReplace(Cached.java:60)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at org.gradle.configurationcache.serialization.codecs.jos.JavaObjectSerializationCodec$WriteReplaceEncoding.encode(JavaObjectSerializationCodec.kt:180)
    	at org.gradle.configurationcache.serialization.codecs.BindingsBackedCodec.encode(BindingsBackedCodec.kt:52)
    	at org.gradle.configurationcache.serialization.DefaultWriteContext.write(Contexts.kt:85)
    	at org.gradle.configurationcache.serialization.beans.BeanPropertyWriterKt.writeNextProperty(BeanPropertyWriter.kt:96)
    	... 152 more
```

### Steps to Reproduce 

Implement something like `signTask.getOnlyIf()`, compile with Gradle 7.6, try running with 7.5.1.
See https://github.com/gradle/gradle/blob/acc6044325b11874e9626d98dec976a0e495cb62/subprojects/signing/src/main/java/org/gradle/plugins/signing/SigningExtension.java#L550-L551

### Your Environment

Plugin compiles with Gradle 7.6, then test executes with Gradle 7.5.1

**Comment by vlsi** [comment]
The workaround is to use reflection:

```kotlin
    /**
     * Gradle 7.6 changed the type of `onlyIf` from `Spec<in Task>` to `SelfDescribingSpec<in Task>`,
     * so we need to use reflection to support slightly older Gradle versions in runtime.
     * @see [NoSuchMethodError org.gradle.api.DefaultTask.getOnlyIf when trying to run plugin compiled with Gradle 7.6 with Gradle 7.5.1](https://github.com/gradle/gradle/issues/23520)
     */
    private fun Task.onlyIfSatisfied() : Boolean {
        val getOnlyIf = DefaultTask::class.java.getMethod("getOnlyIf")
        @Suppress("UNCHECKED_CAST")
        val onlyIf = getOnlyIf.invoke(this) as Spec<in Task>
        return onlyIf.isSatisfiedBy(this)
    }
```

**Comment by jbartok** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and prioritized by them.

**Comment by jbartok** [comment]
Change has been made in:
* https://github.com/gradle/gradle/pull/19428

**Comment by eskatos** [comment]
Note that `getOnlyIf()` is coming from the internal `TaskInternal`.
This is not obvious though because we leak `TaskInternal` via the public `DefaultTask` :shrug:
