### ISSUE TITLE
Using CodeNarc with SpringBoot, Gradle 6.3 results in NoClassDefFoundError

### ISSUE THREAD

**Issue by cmhdave** [gradle/gradle#12958]
I was going through our projects upgrading Gradle to the latest version (6.3) and came across an error with Spring Boot projects where the CodeNarc plugin stops working and fails the build.  I suspect it might be related to the Spring Boot Dependency Management plugin?  Regardless it works with 6.2.2 but not 6.3

### Expected Behavior
I expect that the build will try to run the CodeNarc plugin but might fail because the sample project below is missing a codenarc.xml file.

### Current Behavior
Instead you get a NoClassDefFoundError
```
Execution failed for task ':codenarcMain'.
> java.lang.NoClassDefFoundError: Lgroovy/text/TemplateEngine;
```

### Context
This works with 6.2.2 but stopped working with 6.3

### Steps to Reproduce 
I created a basic Spring Boot project to demonstrate this issue available here:

[https://start.spring.io/#!type=gradle-project&language=groovy&platformVersion=2.2.6.RELEASE&packaging=jar&jvmVersion=1.8&groupId=org.codenarc&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=org.codenarc.demo](https://start.spring.io/#!type=gradle-project&language=groovy&platformVersion=2.2.6.RELEASE&packaging=jar&jvmVersion=1.8&groupId=org.codenarc&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=org.codenarc.demo)

This will create a package with Gradle 6.3. Change the build.gradle to include codenarc in the plugins section like so:

```
plugins {
	id 'org.springframework.boot' version '2.2.6.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'groovy'
	id 'codenarc'
}
```
Then run `gradlew codenarcMain`

### Your Environment
I've been able to reproduce this on both my Mac (Catalina) and on Windows 10.  Both environments use Amazon Corretto JVM

**Comment by cmhdave** [comment]
Thanks for the prompt response (and workaround suggestion).  As there is nothing to be fixed in Gradle I'll go ahead and close this ticket.
