### PR TITLE
Update Scala target computation

### LINKED ISSUE #23905: Gradle 8.0 fails Scala build with isBlank not found in String class error
Steps to reproduce:
1. Build the attached project with `gradle build`

Expected Result:
It should build successfully.

Actual Result:
Fails with this error:
```
[Error] .../scala-example/src/main/scala/scala/example/App.scala:6:15: value isBlank is not a member of String
one error found
```

This project builds fine with Gradle 7.6, and no deprecations are reported either.
[scala-example.tar.gz](https://github.com/gradle/gradle/files/10737891/scala-example.tar.gz)

### PR DESCRIPTION
**Pull request by ljacomet**
Only use release when an explicit toolchain is configured.

Fixes #23905

### CODE REVIEW

**Comment by ljacomet** [comment]
@bot-gradle test RfR

**Comment by ljacomet** [comment]
@bot-gradle test and merge

**Comment by ljacomet** [comment]
@bot-gradle cancel

**Comment by ljacomet** [comment]
@bot-gradle test and merge
