### ISSUE TITLE
gradle 7.3.3 doesn't see automatic module

### ISSUE THREAD

**Issue by blacklion** [gradle/gradle#19524]
### Expected Behavior
`gradlew build` must build my app which uses automatic module.

### Current Behavior
`gradlew build` complains about module `JTransforms`:

```
<hidden-path>\module-info.java:3: error: module not found: JTransforms
	requires JTransforms;
	         ^
warning: using incubating module(s): jdk.incubator.foreign
1 error
1 warning

FAILURE: Build failed with an exception.
```

### Context
I'm using gradle 7.3.3 with JDK 17.
My app uses Jigsaw Modules and depends on JTransforms () which is not converted to Module (yet). I've get name of automatic module name for it with `jar` utility:

```
# jar --file=JTransforms-3.1.jar
No module descriptor found. Derived automatic module.

JTransforms@3.1 automatic
requires java.base mandated
contains org.jtransforms.dct
contains org.jtransforms.dht
contains org.jtransforms.dst
contains org.jtransforms.fft
contains org.jtransforms.utils
```

My `module-info.java` looks like this:

```
module panama.benchmarks.foreign.main {
	requires com.sun.jna;
	requires JTransforms;
	requires jdk.incubator.foreign;
}
```

And my `grade,build` dependencies look like this:

```
dependencies {
  implementation group: 'com.github.wendykierp', name: 'JTransforms', version: '3.1'
  implementation group: 'net.java.dev.jna', name: 'jna', version: '5.10.0'
}
```

It works in IDEA (2021.3.1) but gradle refuse to see `JTransforms` module.

### Steps to Reproduce 
1. Make minimal Java module which depends on `com.github.wendykierp:JTransforms:3.1`
2. Require automatic module JTransforms in this module descriptor
3. Try to build this module with gradle

### Your Environment
gradle 7.3.3
JDK 17.0.3
Windows 10 Pro

Build scan URL: https://scans.gradle.com/s/cvqppzhra2zto

**Comment by blacklion** [comment]
Minimal project which shows problem is https://github.com/blacklion/gradle-issue-19524

**Comment by satsen** [comment]
Can confirm, this issue is very severe

**Comment by satsen** [comment]
It is shocking that no test caught this because any library that doesn't have a module-info.java or Automatic-Module-Name cannot be used anymore. Issue still exists in Gradle 7.4.

**Comment by satsen** [comment]
This issue occurs in one of my project but not in the other, I have no idea why.

**Comment by blacklion** [comment]
> This issue occurs in one of my projects but not in the other, I have no idea why. But in the project that works, there is another problem where one of my libraries does not appear at all as a module

Looks like Gradle is Ok with non-modularized JAR which has `Automatic-Module-Name` property in `META-INF/MANIFEST.MF` but hasn't `module-info` (like JNA), but refuses to understand very old-skool JARs without any special properties.

**Comment by satsen** [comment]
@blacklion Indeed, but the thing is I have 2 projects, both same gradle version, one can use classic JARs, one can't. I don't know why.

**Comment by hrstoyanov** [comment]
I think I just got bitten by this issue .. In Gradle 8.6 .. Incredible this still has not been addressed in 2024! In my case this happens with thsi old java library:
https://central.sonatype.com/artifact/org.dhatim/fastexcel-reader
