### ISSUE TITLE
scala plugin joint compilation succeed without producing bytecode files

### ISSUE THREAD

**Issue by apflieger** [gradle/gradle#13925]
### Expected Behavior
Having a scala project and using joint compilation. When fixing a compilation error on a java class, the compilation succeed but the corresponding class file (bytecode) is absent

### Steps to Reproduce 
1. run compilation on this project with `./gradlew compileScala` : https://github.com/apflieger/gradle-incremental-build
2. Then make the compilation fail on base.Main by putting a syntax error
3. rerun `./gradlew compileScala`, the compilation fails as expected. The class file is deleted.
4. Fix the class and rerun `./gradlew compileScala`, the build succeed but the class file is not created.

### Your Environment
```./gradlew -version```

Gradle 6.5.1

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14.0.1 (Oracle Corporation 14.0.1+7)
OS:           Mac OS X 10.15.6 x86_64

```java -version```
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by ljacomet** [comment]
Can you check if the issue still happens with Gradle 6.6 RC3 just released?

**Comment by apflieger** [comment]
Oh yeah, my usecase work on 6.6
Though, when I manually delete the class file and recompile, it is not regenerated. I'm not sure if it should.

**Comment by jjohannes** [comment]
@apflieger can you clarify if you tried with RC3 or an earlier RC?

**Comment by apflieger** [comment]
I tried gradle-6.6-rc-3

**Comment by ljacomet** [comment]
@apflieger Do file an issue, even though I am not sure Gradle will be able to handle it. But at least we would document the potential limitation.

**Comment by apflieger** [comment]
You mean create a new issue for the usecase of a classfile not beeing outputed after deleting it and recompile?

**Comment by ljacomet** [comment]
> You mean create a new issue for the usecase of a classfile not beeing outputted after deleting it and recompile?

Yes :-)

**Comment by apflieger** [comment]
Here it is https://github.com/gradle/gradle/issues/13984. The title is the same (it is really the same topic)

**Comment by ljacomet** [comment]
Closing this one as the issue was fixed in 6.6 by making Zinc transactional.
