### ISSUE TITLE
Unable to debug an 8.9 Gradle build when using TestKit from Gradle 8.8

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#29589]
### Current Behavior

When trying to debug a build that uses Gradle 8.9 with TestKit from Gradle 8.8 the build fails with:
```
Caused by: java.lang.NoSuchMethodError: 'int org.gradle.api.JavaVersion.getMajorVersionNumber()'	
	at org.gradle.api.internal.initialization.DefaultScriptClassPathResolver.prepareClassPath(DefaultScriptClassPathResolver.java:119)	
	at org.gradle.api.internal.initialization.DefaultBuildLogicBuilder.prepareClassPath(DefaultBuildLogicBuilder.java:55)
```

### Expected Behavior

I can debug a Gradle 8.9 build when using Testkit from Gradle 8.8.

### Context (optional)

This happened as part of the Develocity build. I think https://github.com/gradle/gradle/pull/29176 might cause this when you have the new and old version of `JavaVersion` in the same JVM, aka when you try to debug a build via the tooling API.

### Steps to Reproduce

Set up a build with Gradle 8.8. Create a test that runs a build with Gradle 8.9 via TestKit. Try to debug the test from IDEA.

### Gradle version

8.8

**Comment by mlopatkin** [comment]
This is another instance of #25906.

**Comment by ljacomet** [comment]
Discussed with @donat and closing this one as the specific issue is fixed but the more general problem of the linked issue remains.
