### ISSUE TITLE
Forcing Scala 2.10/2.11 for zinc configuration does not work in 6.x nightly

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#11038]
Hi folks, looking into scala in nightly. 

Our understanding is that new gradle has Zinc version 1.x which is the modern zinc (https://docs.gradle.org/nightly/userguide/scala_plugin.html)
With that said. It seems like if you want to use a specific version of scala for the compiler/library as suggested in “Example 7. Forcing a scala-library dependency for the zinc configuration”, things don’t work.

```
configurations.zinc {
    resolutionStrategy.force "org.scala-lang:scala-library:2.10.6" //something we do Today
}
```

Resulting in

```
Caused by: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
        at scala.xml.NamespaceBinding.<init>(NamespaceBinding.scala:24)
        at scala.xml.TopScope$.<init>(TopScope.scala:17)
        at scala.xml.TopScope$.<clinit>(TopScope.scala)
        at scala.Predef$.<init>(Predef.scala:137)
        at scala.Predef$.<clinit>(Predef.scala)
        at sbt.internal.inc.ScalaInstance.<init>(ScalaInstance.scala:76)
```

If we use 2.11.x, we get things like

```
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/runtime/java8/JFunction0$mcZ$sp
        at sbt.librarymanagement.ResolverFunctions.useSecureResolvers(ResolverExtra.scala:98)
        at sbt.librarymanagement.ResolverFunctions.<init>(ResolverExtra.scala:100)
        at sbt.librarymanagement.Resolver$.<init>(Resolver.scala:24)
        at sbt.librarymanagement.Resolver$.<clinit>(Resolver.scala)
        at sbt.internal.inc.ZincComponentCompiler$.<init>(ZincComponentCompiler.scala:172)
```

so it seems like Zinc only works with 2.12.x+ ? This can bee seen by using the following build file -> https://github.com/nebula-plugins/gradle-nebula-integration/blob/master/scala-zinc-issue/build.gradle and running ./gradlew compileScala.

Our guess right now is that Gradle now uses https://github.com/gradle/gradle/blob/8d0b11481a8c6388a475672010d9e7762acf372e/subprojects/language-scala/src/main/java/org/gradle/language/scala/internal/toolchain/DownloadingScalaToolChain.java#L75 org.scala-sbt:zinc_2.12. So maybe 2.12 is required for the zinc compiler from now on?

If that's the case, maybe the Example 7 should have a note around this?

Also, I'm not very familiar with Scala. My understanding is that if you have 2.12.x in zinc compiler and you have 2.10/2.11 in your project dependencies, the resulting library would be compatible with the version specified on your project, is this correct?

**Comment by ljacomet** [comment]
What you experience is expected, the upgraded Zinc compile in Gradle 6.0 requires Scala 2.12, will add that information to the documentation.

Regarding `DownloadingScalaToolChain`, that's the software model side of the plugins, you can ignore.
Changing the zinc version can be done like:
```
dependencies {
    zinc("org.scala-sbt:zinc_2.12:1.2.5")
}
```

We will also add a clearer error if you force the scala version to an incompatible version without specifying the zinc version.

And yes, the scala version used by zinc can be different than the scala version targeted by compilation.

**Comment by rpalcolea** [comment]
Hi @ljacomet , 

I think the issue would be more on updating the docs instead on this case.

Clear error is always welcome!

This was very helpful, Thanks for confirming the behavior!
