### ISSUE TITLE
JavaCompileSpec.getCompileOptions() can no longer be used in plugins

### ISSUE THREAD

**Issue by TwoStone** [gradle/gradle#4109]
I've written a plugin for using the eclipse compiler for java inside of gradles JavaCompile task.
https://plugins.gradle.org/plugin/de.set.ecj

### Expected Behavior

When the plugin is applied the compilation uses the assigned toolchain.

### Current Behavior

When I upgrade a build that works with Gradle 4.2 to version 4.3 the build fails with a java.lang.NoSuchMethodError: org.gradle.api.internal.tasks.compile.JavaCompileSpec.getCompileOptions()

I know I'm using some internal apis to execute the compiler (see [EclipseCompilerAdapter.java](https://github.com/TwoStone/gradle-eclipse-compiler-plugin/blob/296341ea3499f97ceee3a5fadaf20a5107647788/src/main/java/de/set/gradle/ecj/EclipseCompilerAdapter.java)). I was just wondering that, the method getCompilerOptions is available in the gradle-api.jar but seems to be gone when running the build.
Do you have any recommendations how to solve this problem?

### Context
The plugin is used to compile java sources using the eclipse compiler for java and supporting gradles build cache. 

### Steps to Reproduce (for bugs)

I've created a small github project (https://github.com/TwoStone/gradle-ecj-sample) that show the different behaviors with gradle 4.2, 4.3 and 4.4.1

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/adyg7lqnmfg2y/

**Comment by blindpirate** [comment]
Well, this method's bytecode signature has been changed [here](https://github.com/gradle/gradle/commit/b66e4d0664c49215661a061ba5f5d87d77f54dbb#diff-1af661d61343a1b7ea5805edb740570b) because its return type has been changed. I'm afraid there's nothing we can do: you should use internal API at your own risk. Reflection seems to be the only ugly solution if you have to.
