### ISSUE TITLE
3.4-rc-1 changes compile dependencies to provided in IntelliJ 2016.3.3

### ISSUE THREAD

**Issue by litpho** [gradle/gradle#1276]
When refreshing a module in IntelliJ 2016.3.3 while using Gradle 3.4-rc-1, dependencies marked as 'compile' in build.gradle are marked as 'provided' in IntelliJ.

### Expected Behavior
Compile dependencies should be imported as compile.

### Current Behavior
Compile dependencies are marked as provided.

### Context
I'm trying to run a Spring Boot application from IntelliJ and it fails because it doesn't have the SpringBootApplication class on its runtime classpath.

### Steps to Reproduce (for bugs)
See attached screenshot
![gradlecompileprovided](https://cloud.githubusercontent.com/assets/5185114/22454810/db49b4aa-e788-11e6-9354-d926a5794ac2.PNG)

### Your Environment
Windows 7, Gradle 3.4-rc-1 wrapper and IntelliJ 2016.3.3

**Comment by oehme** [comment]
They should be marked as both `PROVIDED` and `RUNTIME`. Could you show me an example project on GitHub?

**Comment by litpho** [comment]
[Sample project](https://github.com/litpho/gradle-rc)

**Comment by oehme** [comment]
Thanks for the example. The problem only happens with the "Create Module per SourceSet" option. This does not use Gradle's mapping directly, but has some intermediate code contributed by IDEA. It seems this code [removes dependencies that are in multiple scopes](https://github.com/JetBrains/intellij-community/blob/master/plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/util/DependencyResolverImpl.groovy#L473) entries, which leads to the problem you are seeing.

@vladsoroka Can you provide some insight why this duplicate removal code is there? I think having a dependency in multiple scopes is valid, it should not be removed. Gradle 3.4 does not use the `COMPILE` scope anymore. Instead it uses a combination of `PROVIDED`/`RUNTIME`/ `TEST`  as applicable. This makes much more configurations work out of the box (so the user has to customize less), but the duplicate removal code above breaks this simplification.

**Comment by vladsoroka** [comment]
@oehme with the "Create Module per SourceSet" option IDEA tries to resolve dependency scopes based on gradle sourceSet configuration. And the main scopes here are `compile` and `runtime`.
`provided` scope has been considered as something configured explicitly:
1.  using War Plugin conventions (i.e. `providedCompile` and `providedRuntime` configurations)
2. using workaround provided by `IdeaPlugin`, I mean ideaPlugin.model.module.scopes['PROVIDED'].['plus'] option.

In order to honor the second configuration, I had to increase the priority of explicitly configured `provided` dependencies.
Btw, why do you set `JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME` configuration as `provided` by default, I guess this was the cause of the issue?

**Comment by vladsoroka** [comment]
@oehme as discussed, the fix has to be applied to custom dependency resolver of IntelliJ.
@litpho please follow the issue at https://youtrack.jetbrains.com/issue/IDEA-167412

**Comment by oehme** [comment]
Thanks @vladsoroka! I'll close this issue. The workaround is to not use "Module per SourceSet" until the fix in IntelliJ is available.

**Comment by jkschneider** [comment]
@oehme Workaround does not appear to help - project dependencies are added in multiple scopes, but still get a `ClassNotFoundException` on this [simple project](https://cdn-enterprise.discourse.org/gradle/uploads/default/original/2X/3/362bafed738dc46698d287f3539dd94bd3b7f290.zip)

**Comment by oehme** [comment]
@jkschneider that project works fine for me.

**Comment by wmacgyver** [comment]
this is still happening for me with intellJ 2016 3.4, and gradle 3.4. I'm not using gradle wrapper however.

**Comment by oehme** [comment]
As mentioned before, you will need the latest nightly of IDEA. @vladsoroka is there a 2016.3 nightly with the fix too?

**Comment by wmacgyver** [comment]
@oehme oh I didn't realize to resolve it I have to run latest nightly build of intelliJ

**Comment by vladsoroka** [comment]
@oehme there is no 2016.3 nigtly with the fix. The fix should be thoroughly tested in the dev branch and with 2017.1 EAPs then it will be backported to 2016.3.x

**Comment by Abrasha** [comment]
The issue is 100% reproducible with 2016.3.4: https://youtrack.jetbrains.com/issue/IDEA-168710#c=true&rw=1027&rh=683&u=1488032489408

Downgrading to 3.3 helps to avoid this issue.

**Comment by oehme** [comment]
@abrasha please either use the latest IntelliJ nightly or deactivate the "Module per SourceSet" option when you import.

**Comment by vladsoroka** [comment]
fyi, IntelliJ IDEA 2016.3.6 EAP with the fix should be available ~ at 7th of March. 
Your early testing and feedback are very appreciated.

**Comment by marceloverdijk** [comment]
Where can I find the IntelliJ IDEA (Ultimate) 2016.3.6 nightly build? (I'm a licensed user).

**Comment by Abrasha** [comment]
@marceloverdijk, I asked about it in raised ticket

>there is no 2016.3 build with the fix yet, so you can either use EAP from https://www.jetbrains.com/idea/nextversion/ or use Gradle 3.3 until 2017.1 is released (or 2016.3.x update with a fix is released

**Comment by marceloverdijk** [comment]
@vladsoroka mentioned:

> fyi, IntelliJ IDEA 2016.3.6 nightly build with the fix is already available.

**Comment by marceloverdijk** [comment]
@Abrasha but I will try 2017.1 for now.

**Comment by Abrasha** [comment]
Oops, seems that I missed that comment, sorry

**Comment by marceloverdijk** [comment]
@Abrasha No worries, but it seems (too) hard to find the nightly builds :-(

**Comment by marceloverdijk** [comment]
I can confirm it works again with 2017.1 EAP.

**Comment by SetoKaiba** [comment]
The 2017.1 EAP is with correct scope of dependency now. But the run/debug config window of Gradle are with bug.
Do you guys meet the same problem?

**Comment by vladsoroka** [comment]
@marceloverdijk I think, you can get nigthly, eap or release versions easily using toolbax app (https://www.jetbrains.com/toolbox/app)

**Comment by vladsoroka** [comment]
@SetoKaiba  you've faced with another not related to the issue bug, see details at the IntelliJ linked issue.

**Comment by Abrasha** [comment]
@marceloverdijk yesterday I have update Intellij IDEA via Toolbox App and there are issues with Gradle 3.4.

Current Ultimate version: 
```
IntelliJ IDEA 2016.3.5
Build #IU-163.13906.18, built on March 6, 2017
```

**Comment by vladsoroka** [comment]
@Abrasha you use 2016.3.5 but the fixed version of the bug is 2016.3.6

**Comment by marlonwc3** [comment]
There is some expected date for the release of v2016.3.6 ?

**Comment by Idolon-V** [comment]
I still have this issue in the latest Android Studio 3.0 (which is AFAIK build on IDEA 2017.1 codebase). My project consists of one Android application module, two java-library modules and one Java application module. Every `implementation` dependency transforms into `provided` orderEntry in the iml files.
@vladsoroka Should I raise a new issue?

**Comment by oehme** [comment]
@Idolon-V the issue is not that it is provided (that was intentional), but that the corresponding runtime dependency was missing. Are you missing the runtime dependency?

**Comment by cromoteca** [comment]
I'm using Android studio to develop an application with three modules: an Android app, a java Desktop app, and a library of shared code. For the desktop app I use the application plugin and I declare my dependencies as "compile". They are marked as provided in the .iml file and I get a NoClassDefFoundError when I run my main class through the IDE. The app works if I run it with Gradle from the command line.

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-693.11.1.el7.x86_64

**Comment by Idolon-V** [comment]
@oehme Yes, exactly. I'm missing the runtime dependency.

**Comment by Idolon-V** [comment]
> They are marked as provided in the .iml file and I get a NoClassDefFoundError when I run my main class through the IDE. The app works if I run it with Gradle from the command line.  

@cromoteca Same for me

**Comment by oehme** [comment]
@ducrohet which version of IntelliJ is Android Studio 3.0 based on?

**Comment by vladsoroka** [comment]
@oehme The original problem only happened with the "Create Module per SourceSet" option. This option is not relevant for android gradle projects(it's ignored by android plugin code).
The gradle project considered by IntelliJ android plugin as android gradle project if there is at least one android subproject exist.
So, the mentioned in the thread fix doesn't help in case of android gradle project.

> @vladsoroka Should I raise a new issue?

@Idolon-V no, there is already open issue for the IntelliJ android subsystem:
https://youtrack.jetbrains.com/issue/IDEA-170058

**Comment by oehme** [comment]
Thanks Vlad. What's the correlation between this Android subsystem and Android Studio? Are they alternatives?

**Comment by vladsoroka** [comment]
The Android Studio and IntelliJ Android plugin(Android Subsystem at youtrack) use the common codebase.

**Comment by johnny1952** [comment]
I have same problem in Intellij 2018.2
