### ISSUE TITLE
Gradle 8.0 fails Scala build with isBlank not found in String class error

### ISSUE THREAD

**Issue by stamhankar999** [gradle/gradle#23905]
Steps to reproduce:
1. Build the attached project with `gradle build`

Expected Result:
It should build successfully.

Actual Result:
Fails with this error:
```
[Error] .../scala-example/src/main/scala/scala/example/App.scala:6:15: value isBlank is not a member of String
one error found
```

This project builds fine with Gradle 7.6, and no deprecations are reported either.
[scala-example.tar.gz](https://github.com/gradle/gradle/files/10737891/scala-example.tar.gz)

**Comment by rpalcolea** [comment]
@ljacomet I found this interesting, I tend to look at reported scala issues and since we didn't find problems on our side, I downloaded the sample and took a look.

Assuming you want to use JDK11+ which is where `isBlank` was added afaik

The scala compiler is indeed instructed to run for 11 as target:

```
2023-02-15T18:17:32.621-0800 [DEBUG] [org.gradle.api.internal.tasks.scala.NormalizingScalaCompiler] Java compiler arguments: -source 11 -target 11 -d /Users/rperezalcolea/Downloads/scala-example/scala-example/build/classes/scala/main -g -sourcepath  -proc:none -s /Users/rperezalcolea/Downloads/scala-example/scala-example/build/generated/sources/annotationProcessor/scala/main -XDuseUnsharedTable=true -classpath /Users/rperezalcolea/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.9/48bad4bee84f503be847be81ae96d32f6e78d658/scala-library-2.13.9.jar:/Users/rperezalcolea/Downloads/scala-example/scala-example/build/classes
```

However, the cached incremental compiler is using `release` flag for 8

```
2023-02-15T18:17:33.924-0800 [DEBUG] [org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory] [zinc] Running cached compiler 7e43e9b2 for Scala compiler version 2.13.9
2023-02-15T18:17:33.925-0800 [DEBUG] [org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory] [zinc] The Scala compiler is invoked with:
        -deprecation
        -unchecked
        -release:8
        -bootclasspath
```

Using toolchains definitely works 

```
2023-02-15T18:20:42.615-0800 [DEBUG] [org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory] [zinc] Running cached compiler 4b7c6058 for Scala compiler version 2.13.9
2023-02-15T18:20:42.616-0800 [DEBUG] [org.gradle.api.internal.tasks.scala.ZincScalaCompilerFactory] [zinc] The Scala compiler is invoked with:
        -deprecation
        -unchecked
        -release:11
        -bootclasspath
        /Users/rperezalcolea/.gradle/caches/modules-2/files-2.1/org.scala-lang/scala-library/2.13.9/48bad4bee84f503be847be81ae96d32f6e78d658/scala-library-2.13.9.j
```

**Comment by ljacomet** [comment]
* Fixed by #23926
