### ISSUE TITLE
compileIntegrationTestJava fails when upgrading from 6.9.1 to 7.2

### ISSUE THREAD

**Issue by jscancella** [gradle/gradle#18577]
When I upgrade from gradle 6.9.1 to 7.2 my build breaks the `compileIntegrationTestJava` task due to compilation errors 

### Expected Behavior
the code should compile just as in gradle 6.9.1

### Current Behavior
I get the error
```
Execution failed for task ':compileIntegrationTestJava'.
> Compilation failed; see the compiler error output for details.
```

### Context

Works with version 6.9.1, breaks with version 7.2

### Steps to Reproduce 
clone https://github.com/jscancella/bagging
run ./gradlew check

### Your Environment

Build scan URL: https://scans.gradle.com/s/2twsuhtijxphw

**Comment by asodja** [comment]
Does this change fixes that issue:
```
diff --git a/code-quality.gradle b/code-quality.gradle
index 4fa7db3..6ce66f9 100644
--- a/code-quality.gradle
+++ b/code-quality.gradle
@@ -13,8 +13,8 @@ sourceSets {
 }
 
 configurations {
-  integrationTestCompile.extendsFrom testImplementation
-  integrationTestRuntime.extendsFrom testRuntimeOnly
+  integrationTestImplementation.extendsFrom testImplementation
+  integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
 }
 ```
 
 Note that compile and runtime configurations were removed in 7.x, check [upgrade guide](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal)

**Comment by jscancella** [comment]
That fixed it, thank you!
