### ISSUE TITLE
Build error regarding Play Framework templates

### ISSUE THREAD

**Issue by bsautel** [gradle/gradle#2582]
A Play Framework build that passed with gradle 3.5 is broken in gradle 4.0.1. I had a look at the release notes and I did not see any migration procedure regarding Play Framework. There may be a regression in gradle 4, unless I misconfigured something in my project?

### Expected Behavior
The build should pass. It passes with gradle 3.5 using the `./gradlew clean build` command.

### Current Behavior
The same command does not work with gradle 4.0.1.

    > Task :compilePlayBinaryScala
    Pruning sources from previous analysis, due to incompatible CompileSetup.
    [buildDirectory]/app/controllers/HomeController.java:22: error: cannot find symbol
            return ok(index.render(hello.buildHelloMessage()));
                      ^
      symbol:   variable index
      location: class HomeController
    1 error

    FAILURE: Build failed with an exception.

### Steps to Reproduce (for bugs)

Clone [this repository](https://github.com/bsautel/play-java-gradle-example) (which is a simple Play Framework project configured with gradle) and run `./gradlew build`. It works.
Set the gradle wrapper version to `4.0.1` (in the `build.gradle` file), run `./gradlew wrapper` to update the gradle wrapper and run `./gradlew clean build` again. It fails.

### Your Environment
Ubuntu 17.04.

    ------------------------------------------------------------
    Gradle 3.5
    ------------------------------------------------------------
    
    Build time:   2017-04-10 13:37:25 UTC
    Revision:     b762622a185d59ce0cfc9cbc6ab5dd22469e18a6
    
    Groovy:       2.4.10
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
    OS:           Linux 4.10.0-26-generic amd64

    ------------------------------------------------------------
    Gradle 4.0.1
    ------------------------------------------------------------
    
    Build time:   2017-07-07 14:02:41 UTC
    Revision:     38e5dc0f772daecca1d2681885d3d85414eb6826
    
    Groovy:       2.4.11
    Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
    JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
    OS:           Linux 4.10.0-26-generic amd64

Thanks to all the gradle contributors for this wonderful build tool!

**Comment by bmuschko** [comment]
I tried to reproduce the issue but couldn't. First I ran with the checked-in Wrapper (3.5) and then changed the Wrapper to 4.0.1. In both cases your project does not fail with a compilation error. Are you sure you didn't change some other file?

**Comment by bsautel** [comment]
Hi @bmuschko. Thanks for your quick answer!

I did not change any file but I think I forgot to tell in my procedure that it is necessary to run `./gradlew clean` before building again with gradle 4.

I just come to check in an empty Ubuntu Zesty Docker container and I reproduce the issue without changing any file (only if I clean before building with gradle 4).

I wish this will help you to reproduce the issue!

**Comment by bmuschko** [comment]
I followed this procedure:

1. Check out code
2. Run `./gradlew build`
3. Update `gradle/wrapper/gradle-wrapper.properties` to use 4.0.1
4. Run `./gradlew clean`
5. Run `./gradlew build`

Unfortunately, I cannot reproduce the issue. Any chance you can provide us with a build scan? Also, what about CI? Can you set up Travis CI to see if that works for you?

**Comment by bsautel** [comment]
You can find the build scan [here](https://scans.gradle.com/s/d45qkeigfbwaa). I did it in a fresh Docker Ubuntu container.

Note that I noticed it happens only whether the project was previously built in a previous gradle version (3.5 in my case). If I build with gradle 4.0.1 a fresh clone (probably without the gradle cache), I do not get this error.

Hope it helps!

**Comment by bmuschko** [comment]
Looks like an issue with the [Java compiler](https://scans.gradle.com/s/d45qkeigfbwaa/failure?openFailures=WzBd&openStackTraces=WzIse31d#top=0):

```
Caused by: sbt.compiler.CompileFailed: (No message provided)Close stacktrace
at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:72)
at sbt.compiler.JavaTool$class.apply(JavaCompiler.scala:32)
at sbt.compiler.JavaCompiler$JavaTool0.apply(JavaCompiler.scala:59)
at sbt.compiler.JavaCompiler$class.compile(JavaCompiler.scala:20)
at sbt.compiler.JavaCompiler$JavaTool0.compile(JavaCompiler.scala:59)
at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply$mcV$sp(AggressiveCompile.scala:123)
at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:123)
at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileJava$1$1.apply(AggressiveCompile.scala:123)
at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:162)
at sbt.compiler.AggressiveCompile$$anonfun$3.compileJava$1(AggressiveCompile.scala:122)
at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:139)
at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:39)
at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:66)
at sbt.inc.Incremental$.compile(Incremental.scala:38)
at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:153)
at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
at com.typesafe.zinc.Compiler.compile(Compiler.scala:201)
at com.typesafe.zinc.Compiler.compile(Compiler.scala:183)
at com.typesafe.zinc.Compiler.compile(Compiler.scala:174)
at com.typesafe.zinc.Compiler.compile(Compiler.scala:165)
at org.gradle.api.internal.tasks.scala.ZincScalaCompiler$Compiler.execute(ZincScalaCompiler.java:81)
at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:52)
at org.gradle.api.internal.tasks.scala.ZincScalaCompiler.execute(ZincScalaCompiler.java:38)
at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:73)
at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:64)
at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:29)
at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerDaemonServer.execute(AbstractDaemonCompiler.java:91)
at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:88)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
```

I will likely ping someone in the team that is more familiar with Scala/Play projects.

**Comment by bmuschko** [comment]
> Gradle 3.5, Build scan plugin 1.8

Looks like your issue already happens with 3.5. See top of the build scan.

**Comment by bsautel** [comment]
Oh yes, sorry, you're right.

I was switching from 3.5 and 4.0.1 to reproduce the issue and it sounds like I reproduced it also with gradle 3.5 whereas I thought I was with gradle 4.0.1.

[Here](https://scans.gradle.com/s/5kfk74smwzge4) is the build scan of the same failure with gradle 4.0.1.

It sounds like it happens when changing the gradle version in a directory previously built with another gradle version. In the downgrade way, it is not very important, but in the upgrade way it may be annoying.

I noticed with gradle 3.5 it is the same error but gradle 4 adds the following line:

> Pruning sources from previous analysis, due to incompatible CompileSetup.

**Comment by bmuschko** [comment]
We suspect that the issue is the same or related to the issue https://github.com/gradle/gradle/issues/1168.

**Comment by bsautel** [comment]
Ok, I think I understand why.

The compile error tells that a compiled template cannot be found.

> :compilePlayBinaryPlayTwirlTemplates UP-TO-DATE

The Twirl templates are not compiled because they are already up-to-date but they should not after a clean. It is the reason why the Java compiler does not find them.

**Comment by big-guy** [comment]
I'm very sure it's #1168.  This is something we're trying to fix for 4.2.  

As a workaround, can you try adding:
```
    tasks {
        withType(TwirlCompile) {
            doLast {
                fileTree(outputDirectory).files.each {
                    GFileUtils.touch(it)
                }
            }
        }
    }
```

These steps were reproducible for me without the workaround:
1. Delete project's `.gradle`.
2. Build with `./gradew build`.
3. Change Gradle version.
4. Build with `./gradlew build`.
5. Clean `./gradlew clean`.
6. Build with `./gradlew build`. (this would fail)

**Comment by bsautel** [comment]
Hi @big-guy. Indeed, the workaround you suggested fixes the issue.

Note that I just had to adjust it to get it compile:

    tasks.withType(TwirlCompile) {
        doLast {
            fileTree(outputDirectory).files.each {
                GFileUtils.touch(it)
            }
        }
    }

Thanks!

**Comment by bmuschko** [comment]
@bsautel Please be aware that `GFileUtils` is an internal API. You might want to write the method yourself to avoid potential future breakages.

**Comment by bmuschko** [comment]
I am going to close this issue as a duplicate of https://github.com/gradle/gradle/issues/1168.
