### ISSUE TITLE
Annotation processing heavily fails builds with Gradle 4.8+ comparing to 4.7

### ISSUE THREAD

**Issue by soberich** [gradle/gradle#5448]
### Current Behavior
We are experiencing very tough time with trials to build projects with Gradle 4.8 and 4.9 which seems to behave quite differently with adding sourcefiles to existing sourceset
#### Edit
~~It is clearly due to attempt to force annotation processors incremental compilation.
(I would be happy if you say like, hey, this is all JpaModelGen fault, but unfortunately this aggressive  incremental compilation behavior does not herald / harbinger / portend / presage / foreshadow anything great for most of our project in future so I file this bug to loose somehow whatever causes this build failures from Gradle part.~~

we add this lines on groovy
```groovy
sourceSets.main.java.srcDirs += file("$buildDir/classes/java/main")
idea.module.generatedSourceDirs.add(file("$buildDir/classes/java/main"))
```
or kotlin 
```kotlin
java.sourceSets["main"].java.srcDir(file("$buildDir/classes/java/main"))
idea.module.generatedSourceDirs.add(file("$buildDir/classes/java/main"))
```
becouse otherwise with just `generatedSourceDirs` we see

![intellij](https://user-images.githubusercontent.com/25544967/40230666-0c7bf4ac-5aa1-11e8-85cd-79f392395124.png)

### Context
ON 4.7 EVERYTHING WORKS FINE or equally if comment out the line `sourceSets.main.java.srcDirs += file("$buildDir/classes/java/main")`
Changing Gradle from 4.7 to 4.8+ breaks normal build behavior of multi-module projects. The more complex and heavy project is the more it takes to build successfully. Especially when building from IntelliJ and not CLI.

### Steps to Reproduce (for bugs)
Go **https://github.com/soberich/gradle48plus_issue_5448**
`./gradlew build` multiple times (but it still may work fine, please read below)
from our experience starting from the second trial build will fail for at least 1 time IN INTELLIJ. The bigger project is -> the more times this happens. Some times 4-5 time and only on 6th it works.
Unfortunately, even this provided above example does build successfully EVERY TIME from CLI, but from IntelliJ only every second time.. It is very hard to reproduce (especially on small project).
When it fails it says:
```
Executing tasks ':ap:classes :ap:testClasses :classes :testClasses'...

> Task :ap:compileKotlin UP-TO-DATE
> Task :ap:compileJava NO-SOURCE
> Task :ap:processResources NO-SOURCE
> Task :ap:classes UP-TO-DATE
> Task :ap:compileTestKotlin NO-SOURCE
> Task :ap:compileTestJava NO-SOURCE
> Task :ap:processTestResources NO-SOURCE
> Task :ap:testClasses UP-TO-DATE
> Task :ap:jar UP-TO-DATE
> Task :compileKotlin

> Task :compileJava FAILED
error: error reading 
...build\classes\java\main\org\javaee8\validation\Base_.java; ...build\classes\java\main\org\javaee8\validation\Base_.java (The system cannot find the file specified)
error: error reading 
...build\classes\java\main\org\javaee8\validation\Person_.java; ...build\classes\java\main\org\javaee8\validation\Person_.java (The system cannot find the file specified)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
4 actionable tasks: 2 executed, 2 up-to-date
Compilation failed; see the compiler error output for details.
23:52:23: Tasks execution finished ':ap:classes :ap:testClasses :classes :testClasses'.
```  

when we build our common projects - even from CLI ot fails many times or even for ever! So you need to force stop JVM process and rebuild.
This is super inconvenient with tests. When you want to just execute 1 test from IntelliJ - you stuck completely. 
So, for now at a descent project it is impossible to work with Gradle 4.8+ with JpaModelGen, for example, - completely.. with Mapstruct - almost completely with same problems plus all-the-way locking of generated jars (but this is more about IntelliJ and / or Windows 10 problem, **but** it IS even worse with Gradle 4.8+)

_P.S. Even we've waited for `hibernate-jpamodelgen 5.3.0.Final` to be released two-three days ago to file this one, so that no concerns about JpaModelGen beta versions._

### Your Environment
------------------------------------------------------------
Gradle 4.8-rc-1
------------------------------------------------------------

Build time:   2018-05-15 17:32:33 UTC
Revision:     cfb66ee34d37b52c741150a398663618a94d2045

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Windows 10 10.0 amd64

**Comment by oehme** [comment]
We don't force incremental compilation at all. Processors have to opt-in. If they don't, then everything should work exactly like before. I'll have a look at your example project.

**Comment by oehme** [comment]
The example doesn't compile at all, no matter which Gradle version. Can you please provide a working example?

**Comment by oehme** [comment]
The example has a syntax error in one file. I was able to fix it, but you might want to adjust it for others to try out.

**Comment by oehme** [comment]
I can reproduce the issue on the command line by adding `--rerun-tasks`, which is what IntelliJ uses when you click on `rebuild project`.

**Comment by oehme** [comment]
This is unrelated to the changes to annotation processing, but caused by a change to input analysis.

@wolfs We now pass the generated source files to the compiler as "files to compile" because we collect them *before*  the stale output cleaner has run. Can you take this one over?

**Comment by soberich** [comment]
@oehme 
I have updated the issue and repo. Please see above why we add that line.

p.s.
> The reasons this happens is because of this line:
> `sourceSets.main.java.srcDir(file("$buildDir/classes/java/main"))`

this was copied from kotlin btw. It won't work. Only `sourceSets.main.java.srcDirs += file("$buildDir/classes/java/main")` works on groovy for us.

**Comment by wolfs** [comment]
The problem will be fixed in 4.8 RC2. Fixed via #5455.
